/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/city_01.glb --output components/CityModelGenerated.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    taxi: THREE.Mesh
    ['road-bend']: THREE.Mesh
    ['road-bend001']: THREE.Mesh
    ['road-bend002']: THREE.Mesh
    ['road-bend003']: THREE.Mesh
    ['road-crossing']: THREE.Mesh
    ['road-straight']: THREE.Mesh
    ['road-straight002']: THREE.Mesh
    ['road-straight003']: THREE.Mesh
    ['road-straight004']: THREE.Mesh
    ['road-straight005']: THREE.Mesh
    ['road-straight006']: THREE.Mesh
    ['road-straight007']: THREE.Mesh
    ['road-straight008']: THREE.Mesh
    ['road-straight009']: THREE.Mesh
    ['road-straight010']: THREE.Mesh
    ['road-straight011']: THREE.Mesh
    ['tile-low']: THREE.Mesh
    ['tile-low001']: THREE.Mesh
    ['tile-low002']: THREE.Mesh
    ['tile-low003']: THREE.Mesh
    ['tile-low004']: THREE.Mesh
    ['tile-low005']: THREE.Mesh
    ['tile-low006']: THREE.Mesh
    ['tile-low007']: THREE.Mesh
    ['tile-low008']: THREE.Mesh
    ['building-a']: THREE.Mesh
    ['building-d']: THREE.Mesh
    ['building-n']: THREE.Mesh
    ['building-o']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
    ['colormap.001']: THREE.MeshStandardMaterial
    ['colormap.003']: THREE.MeshStandardMaterial
    ['colormap.002']: THREE.MeshStandardMaterial
    ['colormap.004']: THREE.MeshStandardMaterial
    ['colormap.005']: THREE.MeshStandardMaterial
    ['colormap.006']: THREE.MeshStandardMaterial
    ['colormap.007']: THREE.MeshStandardMaterial
    ['colormap.008']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/city_01.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <group name="PathNode_01" position={[0.5, 0, -0.5]} userData={{ name: 'PathNode_01', next_nodes: '[ "PathNode_02" ]' }} />
        <group name="PathNode_02" position={[-3.5, 0, -0.5]} userData={{ name: 'PathNode_02', next_nodes: '["PathNode_03" ]' }} />
        <group name="PathNode_03" position={[-3.5, 0, 3.5]} userData={{ name: 'PathNode_03', next_nodes: '[ "PathNode_04"]' }} />
        <group name="PathNode_04" position={[0.5, 0, 3.5]} userData={{ name: 'PathNode_04', next_nodes: '[ "PathNode_01"]' }} />
        <mesh name="taxi" geometry={nodes.taxi.geometry} material={materials.colormap} rotation={[Math.PI / 2, 0, 0]} scale={0.198} userData={{ name: 'taxi' }} />
        <mesh name="road-bend" geometry={nodes['road-bend'].geometry} material={materials['colormap.001']} position={[0.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-bend' }} />
        <mesh name="road-bend001" geometry={nodes['road-bend001'].geometry} material={materials['colormap.001']} position={[-3.5, 0, -0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-bend.001' }} />
        <mesh name="road-bend002" geometry={nodes['road-bend002'].geometry} material={materials['colormap.001']} position={[-3.5, 0, 3.5]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'road-bend.002' }} />
        <mesh name="road-bend003" geometry={nodes['road-bend003'].geometry} material={materials['colormap.001']} position={[0.5, 0, 3.5]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'road-bend.003' }} />
        <mesh name="road-crossing" geometry={nodes['road-crossing'].geometry} material={materials['colormap.003']} position={[-1.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-crossing' }} />
        <mesh name="road-straight" geometry={nodes['road-straight'].geometry} material={materials['colormap.002']} position={[-0.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight' }} />
        <mesh name="road-straight002" geometry={nodes['road-straight002'].geometry} material={materials['colormap.002']} position={[-2.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.002' }} />
        <mesh name="road-straight003" geometry={nodes['road-straight003'].geometry} material={materials['colormap.002']} position={[0.5, 0, 0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.003' }} />
        <mesh name="road-straight004" geometry={nodes['road-straight004'].geometry} material={materials['colormap.002']} position={[0.5, 0, 1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.004' }} />
        <mesh name="road-straight005" geometry={nodes['road-straight005'].geometry} material={materials['colormap.002']} position={[0.5, 0, 2.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.005' }} />
        <mesh name="road-straight006" geometry={nodes['road-straight006'].geometry} material={materials['colormap.002']} position={[-3.5, 0, 0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.006' }} />
        <mesh name="road-straight007" geometry={nodes['road-straight007'].geometry} material={materials['colormap.002']} position={[-3.5, 0, 1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.007' }} />
        <mesh name="road-straight008" geometry={nodes['road-straight008'].geometry} material={materials['colormap.002']} position={[-3.5, 0, 2.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.008' }} />
        <mesh name="road-straight009" geometry={nodes['road-straight009'].geometry} material={materials['colormap.002']} position={[-2.5, 0, 3.5]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'road-straight.009' }} />
        <mesh name="road-straight010" geometry={nodes['road-straight010'].geometry} material={materials['colormap.002']} position={[-1.5, 0, 3.5]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'road-straight.010' }} />
        <mesh name="road-straight011" geometry={nodes['road-straight011'].geometry} material={materials['colormap.002']} position={[-0.5, 0, 3.5]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'road-straight.011' }} />
        <mesh name="tile-low" geometry={nodes['tile-low'].geometry} material={materials['colormap.004']} position={[-0.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low' }} />
        <mesh name="tile-low001" geometry={nodes['tile-low001'].geometry} material={materials['colormap.004']} position={[-1.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.001' }} />
        <mesh name="tile-low002" geometry={nodes['tile-low002'].geometry} material={materials['colormap.004']} position={[-2.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.002' }} />
        <mesh name="tile-low003" geometry={nodes['tile-low003'].geometry} material={materials['colormap.004']} position={[-0.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.003' }} />
        <mesh name="tile-low004" geometry={nodes['tile-low004'].geometry} material={materials['colormap.004']} position={[-1.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.004' }} />
        <mesh name="tile-low005" geometry={nodes['tile-low005'].geometry} material={materials['colormap.004']} position={[-2.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.005' }} />
        <mesh name="tile-low006" geometry={nodes['tile-low006'].geometry} material={materials['colormap.004']} position={[-0.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.006' }} />
        <mesh name="tile-low007" geometry={nodes['tile-low007'].geometry} material={materials['colormap.004']} position={[-1.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.007' }} />
        <mesh name="tile-low008" geometry={nodes['tile-low008'].geometry} material={materials['colormap.004']} position={[-2.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.008' }} />
        <mesh name="building-a" geometry={nodes['building-a'].geometry} material={materials['colormap.005']} position={[-2, 0, 1]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'building-a' }} />
        <mesh name="building-d" geometry={nodes['building-d'].geometry} material={materials['colormap.006']} position={[-0.5, 0, 1]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'building-d' }} />
        <mesh name="building-n" geometry={nodes['building-n'].geometry} material={materials['colormap.007']} position={[-0.25, 0, 2.75]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-n' }} />
        <mesh name="building-o" geometry={nodes['building-o'].geometry} material={materials['colormap.008']} position={[-2.9, 0, 1.9]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'building-o' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/city_01.glb')
