/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/box_long.glb --output generated_components/box_long.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['box-long']: THREE.Mesh
  }
  materials: {
    ['colormap.019']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/box_long.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <mesh name="box-long" geometry={nodes['box-long'].geometry} material={materials['colormap.019']} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'box-long' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/box_long.glb')
