/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/maxwell.glb --output generated_components/MaxwellGenerated.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React, { forwardRef, useImperativeHandle, useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

export type ActionName = 'agreeing' | 'cellphone_convo' | 'dismiss' | 'handshake' | 'point_ahead' | 'salute.001' | 'shakeitoff' | 'stretching' | 'talking'

export interface MaxwellRef {
  playAnimation: (name: ActionName | null) => void
}

type GLTFResult = GLTF & {
  nodes: {
    max_model: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    PolygonOffice_Charaters: THREE.MeshStandardMaterial
  }
}

export const Model = forwardRef<MaxwellRef, React.ComponentProps<'group'>>(function Model(props, ref) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(getAssetPath('models/maxwell.glb'))
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  const currentAction = useRef<THREE.AnimationAction | null>(null)

  useImperativeHandle(ref, () => ({
    playAnimation: (name: ActionName | null) => {
      if (currentAction.current) {
        currentAction.current.fadeOut(0.3)
      }
      if (name === null) {
        currentAction.current = null
        return
      }
      const action = actions[name]
      if (action) {
        action.reset()
        action.fadeIn(0.3)
        action.play()
        currentAction.current = action
      }
    },
  }))

  useEffect(() => {
    return () => {
      if (currentAction.current) {
        currentAction.current.stop()
      }
    }
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="maxwell_armature" position={[-1.475, 7.593, 1.854]} rotation={[Math.PI / 2, 0, -3.086]} scale={0.00005} userData={{ name: 'maxwell_armature' }}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="max_model" geometry={nodes.max_model.geometry} material={materials.PolygonOffice_Charaters} skeleton={nodes.max_model.skeleton} userData={{ name: 'max_model' }} />
        </group>
      </group>
    </group>
  )
})

useGLTF.preload(getAssetPath('models/maxwell.glb'))
