/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/nutcracker.glb --output generated_components/nutcracker.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    nutcracker: THREE.Mesh
  }
  materials: {
    ['colormap.061']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/nutcracker.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <mesh name="nutcracker" geometry={nodes.nutcracker.geometry} material={materials['colormap.061']} position={[-8.199, 1, 11.07]} rotation={[Math.PI / 2, 0, -1.208]} userData={{ name: 'nutcracker' }} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/nutcracker.glb'))
