/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pizza_03.glb --output generated_components/pizza_03.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    ['pizza-box002']: THREE.Mesh
    ['pizza-box002_1']: THREE.Mesh
  }
  materials: {
    ['colormap.058']: THREE.MeshStandardMaterial
    ['colormap.060']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/pizza_03.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <group name="pizza006" position={[-3.798, 4.188, 10.632]} rotation={[Math.PI / 2, 0, 1.192]} scale={0.179} userData={{ name: 'pizza.006', ant_landscape: {} }}>
          <mesh name="pizza-box002" geometry={nodes['pizza-box002'].geometry} material={materials['colormap.058']} />
          <mesh name="pizza-box002_1" geometry={nodes['pizza-box002_1'].geometry} material={materials['colormap.060']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/pizza_03.glb'))
