/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/present_green_round.glb --output components/present_green_round.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['present-b-round']: THREE.Mesh
  }
  materials: {
    ['colormap.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/present_green_round.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <mesh name="present-b-round" geometry={nodes['present-b-round'].geometry} material={materials['colormap.001']} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'present-b-round' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/present_green_round.glb')
