/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/taxi.glb --output generated_components/TaxiModelGenerated.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    Scene148: THREE.Mesh
    Scene148_1: THREE.Mesh
    Scene148_2: THREE.Mesh
  }
  materials: {
    Synty_Palette_A: THREE.MeshStandardMaterial
    Glass_01: THREE.MeshStandardMaterial
    ['PolygonCity_01_A.006']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/taxi.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <group name="taxi_cab002" position={[-4.661, 0, 8.94]} rotation={[Math.PI, 0, Math.PI]} userData={{ name: 'taxi_cab.002' }}>
          <mesh name="Scene148" geometry={nodes.Scene148.geometry} material={materials.Synty_Palette_A} />
          <mesh name="Scene148_1" geometry={nodes.Scene148_1.geometry} material={materials.Glass_01} />
          <mesh name="Scene148_2" geometry={nodes.Scene148_2.geometry} material={materials['PolygonCity_01_A.006']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/taxi.glb'))
