/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/the_og_shop.glb --output generated_components/the_og_shop.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    shop_og: THREE.Mesh
  }
  materials: {
    ['colormap.005']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/the_og_shop.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <mesh name="shop_og" geometry={nodes.shop_og.geometry} material={materials['colormap.005']} position={[-7.326, 0, 10.822]} rotation={[Math.PI / 2, 0, 0]} scale={1.303} userData={{ name: 'shop_og' }} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/the_og_shop.glb'))
