/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/the_shop.glb --output generated_components/the_shop.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    walls: THREE.Mesh
    windows: THREE.Mesh
    back_wall: THREE.Mesh
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    chairDesk_1: THREE.Mesh
    chairDesk_2: THREE.Mesh
    desk_1: THREE.Mesh
    desk_2: THREE.Mesh
    kitchenCabinet_1: THREE.Mesh
    kitchenCabinet_2: THREE.Mesh
    kitchenCabinet_3: THREE.Mesh
    kitchenCabinetUpper_1: THREE.Mesh
    kitchenCabinetUpper_2: THREE.Mesh
    kitchenCabinetUpper_3: THREE.Mesh
    kitchenFridgeLarge_1: THREE.Mesh
    kitchenFridgeLarge_2: THREE.Mesh
    kitchenStove_1: THREE.Mesh
    kitchenStove_2: THREE.Mesh
    kitchenStove_3: THREE.Mesh
    kitchenStove_4: THREE.Mesh
    kitchenStove_5: THREE.Mesh
    tableCoffeeGlass_1: THREE.Mesh
    tableCoffeeGlass_2: THREE.Mesh
    coatRackStanding: THREE.Mesh
    lampRoundFloor_1: THREE.Mesh
    lampRoundFloor_2: THREE.Mesh
    plantSmall3_1: THREE.Mesh
    plantSmall3_2: THREE.Mesh
    pottedPlant_1: THREE.Mesh
    pottedPlant_2: THREE.Mesh
    pottedPlant_3: THREE.Mesh
    kitchenCoffeeMachine_1: THREE.Mesh
    kitchenCoffeeMachine_2: THREE.Mesh
    kitchenCoffeeMachine_3: THREE.Mesh
    rugRounded_1: THREE.Mesh
    rugRounded_2: THREE.Mesh
    doorway_1: THREE.Mesh
    doorway_2: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    bedDouble_1: THREE.Mesh
    bedDouble_2: THREE.Mesh
    loungeSofa: THREE.Mesh
  }
  materials: {
    metalDark: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    metalMedium: THREE.MeshStandardMaterial
    carpet: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    ['metal.004']: THREE.MeshStandardMaterial
    ['wood.002']: THREE.MeshStandardMaterial
    woodDark: THREE.MeshStandardMaterial
    ['wood.007']: THREE.MeshStandardMaterial
    ['woodDark.001']: THREE.MeshStandardMaterial
    ['metal.007']: THREE.MeshStandardMaterial
    ['metalLight.001']: THREE.MeshStandardMaterial
    ['metalMedium.001']: THREE.MeshStandardMaterial
    ['metal.005']: THREE.MeshStandardMaterial
    ['wood.003']: THREE.MeshStandardMaterial
    ['metalDark.001']: THREE.MeshStandardMaterial
    carpetWhite: THREE.MeshStandardMaterial
    ['glass.001']: THREE.MeshStandardMaterial
    ['metal.006']: THREE.MeshStandardMaterial
    ['glass.002']: THREE.MeshStandardMaterial
    ['wood.009']: THREE.MeshStandardMaterial
    ['metal.009']: THREE.MeshStandardMaterial
    lamp: THREE.MeshStandardMaterial
    ['wood.010']: THREE.MeshStandardMaterial
    plant: THREE.MeshStandardMaterial
    ['wood.011']: THREE.MeshStandardMaterial
    ['woodDark.002']: THREE.MeshStandardMaterial
    ['plant.001']: THREE.MeshStandardMaterial
    ['metalMedium.004']: THREE.MeshStandardMaterial
    ['metal.010']: THREE.MeshStandardMaterial
    ['carpetWhite.002']: THREE.MeshStandardMaterial
    carpetDarker: THREE.MeshStandardMaterial
    ['carpet.003']: THREE.MeshStandardMaterial
    ['wood.001']: THREE.MeshStandardMaterial
    ['metal.002']: THREE.MeshStandardMaterial
    ['carpetWhite.001']: THREE.MeshStandardMaterial
    ['carpet.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/the_shop.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <mesh name="walls" geometry={nodes.walls.geometry} material={materials.metalDark} position={[-7.298, 0, 11]} scale={[1.302, 1, 1]} userData={{ name: 'walls' }} />
        <mesh name="windows" geometry={nodes.windows.geometry} material={materials['Material.001']} position={[-6.061, 1.065, 10.123]} scale={0.065} userData={{ name: 'windows' }} />
        <mesh name="back_wall" geometry={nodes.back_wall.geometry} material={materials.metalDark} position={[-8.535, 2.421, 10.123]} rotation={[0, 0, -Math.PI]} scale={0.065} userData={{ name: 'back_wall' }} />
        <group name="tutorial_stand" position={[-6.547, 1.106, 10.675]} rotation={[0, -0.358, 0]} scale={0.106} userData={{ name: 'tutorial_stand' }}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.002']} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="chairDesk" position={[-7.07, 1, 11.027]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'chairDesk' }}>
          <mesh name="chairDesk_1" geometry={nodes.chairDesk_1.geometry} material={materials.metalMedium} />
          <mesh name="chairDesk_2" geometry={nodes.chairDesk_2.geometry} material={materials.carpet} />
        </group>
        <group name="desk" position={[-7.652, 1, 10.837]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'desk' }}>
          <mesh name="desk_1" geometry={nodes.desk_1.geometry} material={materials.wood} />
          <mesh name="desk_2" geometry={nodes.desk_2.geometry} material={materials.metal} />
        </group>
        <group name="kitchenCabinet" position={[-6.555, 1, 12.801]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'kitchenCabinet' }}>
          <mesh name="kitchenCabinet_1" geometry={nodes.kitchenCabinet_1.geometry} material={materials['metal.004']} />
          <mesh name="kitchenCabinet_2" geometry={nodes.kitchenCabinet_2.geometry} material={materials['wood.002']} />
          <mesh name="kitchenCabinet_3" geometry={nodes.kitchenCabinet_3.geometry} material={materials.woodDark} />
        </group>
        <group name="kitchenCabinetUpper" position={[-6.296, 1.724, 12.779]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'kitchenCabinetUpper' }}>
          <mesh name="kitchenCabinetUpper_1" geometry={nodes.kitchenCabinetUpper_1.geometry} material={materials['wood.007']} />
          <mesh name="kitchenCabinetUpper_2" geometry={nodes.kitchenCabinetUpper_2.geometry} material={materials['woodDark.001']} />
          <mesh name="kitchenCabinetUpper_3" geometry={nodes.kitchenCabinetUpper_3.geometry} material={materials['metal.007']} />
        </group>
        <group name="kitchenFridgeLarge" position={[-6.467, 1, 13.713]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'kitchenFridgeLarge' }}>
          <mesh name="kitchenFridgeLarge_1" geometry={nodes.kitchenFridgeLarge_1.geometry} material={materials['metalLight.001']} />
          <mesh name="kitchenFridgeLarge_2" geometry={nodes.kitchenFridgeLarge_2.geometry} material={materials['metalMedium.001']} />
        </group>
        <group name="kitchenStove" position={[-6.516, 1, 13.259]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'kitchenStove' }}>
          <mesh name="kitchenStove_1" geometry={nodes.kitchenStove_1.geometry} material={materials['metal.005']} />
          <mesh name="kitchenStove_2" geometry={nodes.kitchenStove_2.geometry} material={materials['wood.003']} />
          <mesh name="kitchenStove_3" geometry={nodes.kitchenStove_3.geometry} material={materials['metalDark.001']} />
          <mesh name="kitchenStove_4" geometry={nodes.kitchenStove_4.geometry} material={materials.carpetWhite} />
          <mesh name="kitchenStove_5" geometry={nodes.kitchenStove_5.geometry} material={materials['glass.001']} />
        </group>
        <group name="tableCoffeeGlass" position={[-7.622, 1, 13.404]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'tableCoffeeGlass' }}>
          <mesh name="tableCoffeeGlass_1" geometry={nodes.tableCoffeeGlass_1.geometry} material={materials['metal.006']} />
          <mesh name="tableCoffeeGlass_2" geometry={nodes.tableCoffeeGlass_2.geometry} material={materials['glass.002']} />
        </group>
        <mesh name="coatRackStanding" geometry={nodes.coatRackStanding.geometry} material={materials['wood.009']} position={[-8.353, 1, 14.009]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'coatRackStanding' }} />
        <group name="lampRoundFloor" position={[-8.22, 1, 11.237]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'lampRoundFloor' }}>
          <mesh name="lampRoundFloor_1" geometry={nodes.lampRoundFloor_1.geometry} material={materials['metal.009']} />
          <mesh name="lampRoundFloor_2" geometry={nodes.lampRoundFloor_2.geometry} material={materials.lamp} />
        </group>
        <group name="plantSmall3" position={[-7.517, 1.23, 13.118]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'plantSmall3' }}>
          <mesh name="plantSmall3_1" geometry={nodes.plantSmall3_1.geometry} material={materials['wood.010']} />
          <mesh name="plantSmall3_2" geometry={nodes.plantSmall3_2.geometry} material={materials.plant} />
        </group>
        <group name="pottedPlant" position={[-8.306, 1, 10.343]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'pottedPlant' }}>
          <mesh name="pottedPlant_1" geometry={nodes.pottedPlant_1.geometry} material={materials['wood.011']} />
          <mesh name="pottedPlant_2" geometry={nodes.pottedPlant_2.geometry} material={materials['woodDark.002']} />
          <mesh name="pottedPlant_3" geometry={nodes.pottedPlant_3.geometry} material={materials['plant.001']} />
        </group>
        <group name="kitchenCoffeeMachine" position={[-6.4, 1.42, 13.023]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'kitchenCoffeeMachine' }}>
          <mesh name="kitchenCoffeeMachine_1" geometry={nodes.kitchenCoffeeMachine_1.geometry} material={materials['metalMedium.004']} />
          <mesh name="kitchenCoffeeMachine_2" geometry={nodes.kitchenCoffeeMachine_2.geometry} material={materials['metal.010']} />
          <mesh name="kitchenCoffeeMachine_3" geometry={nodes.kitchenCoffeeMachine_3.geometry} material={materials['carpetWhite.002']} />
        </group>
        <group name="rugRounded" position={[-7.978, 1, 12.523]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'rugRounded' }}>
          <mesh name="rugRounded_1" geometry={nodes.rugRounded_1.geometry} material={materials.carpetDarker} />
          <mesh name="rugRounded_2" geometry={nodes.rugRounded_2.geometry} material={materials['carpet.003']} />
        </group>
        <group name="doorway" position={[-6.951, 0.972, 13.074]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'doorway' }}>
          <mesh name="doorway_1" geometry={nodes.doorway_1.geometry} material={materials['wood.001']} />
          <mesh name="doorway_2" geometry={nodes.doorway_2.geometry} material={materials['metal.002']} />
        </group>
        <group name="Cube002" position={[-7.196, 1.215, 13.113]} scale={[-0.081, -0.02, -0.014]} userData={{ name: 'Cube.002' }}>
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['carpetWhite.002']} />
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.carpetDarker} />
        </group>
        <group name="bedDouble" position={[-7.91, 1, 11.922]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'bedDouble' }}>
          <mesh name="bedDouble_1" geometry={nodes.bedDouble_1.geometry} material={materials['carpetWhite.001']} />
          <mesh name="bedDouble_2" geometry={nodes.bedDouble_2.geometry} material={materials['carpet.001']} />
        </group>
        <mesh name="loungeSofa" geometry={nodes.loungeSofa.geometry} material={materials['carpet.003']} position={[-8.055, 0.972, 13.611]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'loungeSofa' }} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/the_shop.glb'))
