/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/the_og_shop.glb --output generated_components/the_og_shop.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    Scene12125: THREE.Mesh
    Scene12125_1: THREE.Mesh
    Scene12128: THREE.Mesh
    Scene12128_1: THREE.Mesh
    Scene12129: THREE.Mesh
    Scene12129_1: THREE.Mesh
    Scene12131: THREE.Mesh
    Scene12131_1: THREE.Mesh
    SM_Bld_Shop_08: THREE.Mesh
    SM_Bld_Shop_08001: THREE.Mesh
    SM_Bld_Shop_08002: THREE.Mesh
  }
  materials: {
    Glass_01: THREE.MeshStandardMaterial
    Synty_Palette_A: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/the_og_shop.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <group name="SM_Prop_Skylight_01_Glass_1001" position={[-1.966, -1.294, 6.017]} userData={{ name: 'SM_Prop_Skylight_01_Glass_1.001', ant_landscape: {} }}>
          <mesh name="Scene12125" geometry={nodes.Scene12125.geometry} material={materials.Glass_01} />
          <mesh name="Scene12125_1" geometry={nodes.Scene12125_1.geometry} material={materials.Synty_Palette_A} />
        </group>
        <group name="SM_Prop_Skylight_01_Glass_1002" position={[-1.966, 0.132, 6.017]} userData={{ name: 'SM_Prop_Skylight_01_Glass_1.002', ant_landscape: {} }}>
          <mesh name="Scene12128" geometry={nodes.Scene12128.geometry} material={materials.Glass_01} />
          <mesh name="Scene12128_1" geometry={nodes.Scene12128_1.geometry} material={materials.Synty_Palette_A} />
        </group>
        <group name="SM_Prop_Skylight_01_Glass_1003" position={[-1.966, 1.553, 6.017]} userData={{ name: 'SM_Prop_Skylight_01_Glass_1.003', ant_landscape: {} }}>
          <mesh name="Scene12129" geometry={nodes.Scene12129.geometry} material={materials.Glass_01} />
          <mesh name="Scene12129_1" geometry={nodes.Scene12129_1.geometry} material={materials.Synty_Palette_A} />
        </group>
        <group name="SM_Prop_Skylight_01_Glass_1004" position={[-4.19, -1.294, 6.017]} userData={{ name: 'SM_Prop_Skylight_01_Glass_1.004', ant_landscape: {} }}>
          <mesh name="Scene12131" geometry={nodes.Scene12131.geometry} material={materials.Glass_01} />
          <mesh name="Scene12131_1" geometry={nodes.Scene12131_1.geometry} material={materials.Synty_Palette_A} />
        </group>
        <mesh name="SM_Bld_Shop_08" geometry={nodes.SM_Bld_Shop_08.geometry} material={materials.Synty_Palette_A} position={[-3, 0, 10]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Bld_Shop_08', ant_landscape: {} }} />
        <mesh name="SM_Bld_Shop_08001" geometry={nodes.SM_Bld_Shop_08001.geometry} material={materials.Synty_Palette_A} position={[-7.169, 0, 10]} rotation={[Math.PI / 2, 0, 1.571]} scale={0.002} userData={{ name: 'SM_Bld_Shop_08.001', ant_landscape: {} }} />
        <mesh name="SM_Bld_Shop_08002" geometry={nodes.SM_Bld_Shop_08002.geometry} material={materials.Synty_Palette_A} position={[-7.169, 0, 11]} rotation={[Math.PI / 2, 0, 1.571]} scale={0.002} userData={{ name: 'SM_Bld_Shop_08.002', ant_landscape: {} }} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/the_og_shop.glb'))
