/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tutorial_01.glb --output generated_components/TutorialModelGenerated.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    ['tree-large']: THREE.Mesh
    ['tree-large001']: THREE.Mesh
    ['tree-small']: THREE.Mesh
    ['tree-small001']: THREE.Mesh
    ['tree-large002']: THREE.Mesh
    ['tree-small003']: THREE.Mesh
    ['road-end001']: THREE.Mesh
    ['road-end002']: THREE.Mesh
    ['road-end003']: THREE.Mesh
    ['road-end004']: THREE.Mesh
    ['road-end005']: THREE.Mesh
    ['road-end006']: THREE.Mesh
    ['road-straight']: THREE.Mesh
    ['road-straight001']: THREE.Mesh
    ['road-straight002']: THREE.Mesh
    ['road-straight003']: THREE.Mesh
    ['road-straight004']: THREE.Mesh
    ['road-straight005']: THREE.Mesh
    ['road-straight006']: THREE.Mesh
    ['road-straight007']: THREE.Mesh
    ['road-straight008']: THREE.Mesh
    ['road-straight009']: THREE.Mesh
    ['road-straight010']: THREE.Mesh
    ['road-straight011']: THREE.Mesh
    ['road-straight012']: THREE.Mesh
    ['road-straight013']: THREE.Mesh
    ['road-straight014']: THREE.Mesh
    ['road-straight015']: THREE.Mesh
    ['road-straight016']: THREE.Mesh
    ['road-straight042']: THREE.Mesh
    ['road-straight043']: THREE.Mesh
    ['road-straight056']: THREE.Mesh
    ['road-straight061']: THREE.Mesh
    ['road-straight062']: THREE.Mesh
    ['road-straight063']: THREE.Mesh
    ['road-straight064']: THREE.Mesh
    ['road-straight065']: THREE.Mesh
    ['road-straight066']: THREE.Mesh
    ['road-straight067']: THREE.Mesh
    ['road-straight068']: THREE.Mesh
    ['road-straight069']: THREE.Mesh
    ['road-straight070']: THREE.Mesh
    ['road-straight071']: THREE.Mesh
    ['road-straight072']: THREE.Mesh
    ['road-straight073']: THREE.Mesh
    ['road-straight095']: THREE.Mesh
    ['road-straight096']: THREE.Mesh
    ['road-straight097']: THREE.Mesh
    ['road-straight098']: THREE.Mesh
    ['road-intersection']: THREE.Mesh
    ['road-crossroad']: THREE.Mesh
    ['road-crossroad005']: THREE.Mesh
    ['road-straight099']: THREE.Mesh
    ['road-crossroad-line']: THREE.Mesh
    ['road-crossroad-line001']: THREE.Mesh
    ['road-crossroad-line003']: THREE.Mesh
    ['road-crossroad-line004']: THREE.Mesh
    ['road-end008']: THREE.Mesh
    ['road-straight075']: THREE.Mesh
    ['road-straight094']: THREE.Mesh
    ['road-bend-square']: THREE.Mesh
    ['road-end007']: THREE.Mesh
    ['road-end009']: THREE.Mesh
    suv: THREE.Mesh
    suv001: THREE.Mesh
    ['tractor-shovel']: THREE.Mesh
    ['building-type-a']: THREE.Mesh
    ['building-type-b']: THREE.Mesh
    ['building-type-l']: THREE.Mesh
    ['building-type-a002']: THREE.Mesh
    ['building-type-b001']: THREE.Mesh
    ['building-type-l001']: THREE.Mesh
    ['building-type-a003']: THREE.Mesh
    ['building-type-b002']: THREE.Mesh
    ['building-type-l003']: THREE.Mesh
    ['building-type-a006']: THREE.Mesh
    ['building-type-b004']: THREE.Mesh
    ['building-type-b009']: THREE.Mesh
    ['building-type-a015']: THREE.Mesh
    ['building-type-b011']: THREE.Mesh
    ['building-type-l010']: THREE.Mesh
    ['building-type-a001']: THREE.Mesh
    ['building-type-c001']: THREE.Mesh
    ['building-type-a004']: THREE.Mesh
    ['building-type-c005']: THREE.Mesh
    ['building-type-a005']: THREE.Mesh
    ['building-type-b003']: THREE.Mesh
    ['building-type-l004']: THREE.Mesh
    ['building-type-b013']: THREE.Mesh
    ['building-type-c015']: THREE.Mesh
    ['building-type-c017']: THREE.Mesh
    ['building-type-a019']: THREE.Mesh
    ['building-type-b015']: THREE.Mesh
    ['building-type-c016']: THREE.Mesh
    ['building-type-c019']: THREE.Mesh
    ['building-type-l015']: THREE.Mesh
    ['building-type-b019']: THREE.Mesh
    ['building-type-c021']: THREE.Mesh
    ['tile-low027']: THREE.Mesh
    ['tile-low028']: THREE.Mesh
    ['tile-low029']: THREE.Mesh
    ['tile-low030']: THREE.Mesh
    ['tile-low031']: THREE.Mesh
    ['tile-low032']: THREE.Mesh
    ['tile-low033']: THREE.Mesh
    ['tile-low034']: THREE.Mesh
    ['tile-low035']: THREE.Mesh
    ['tile-low089']: THREE.Mesh
    ['tile-low090']: THREE.Mesh
    ['tile-low092']: THREE.Mesh
    ['tile-low093']: THREE.Mesh
    ['tile-low095']: THREE.Mesh
    ['tile-low096']: THREE.Mesh
    ['tile-low009']: THREE.Mesh
    ['tile-low010']: THREE.Mesh
    ['tile-low011']: THREE.Mesh
    ['tile-low012']: THREE.Mesh
    ['tile-low013']: THREE.Mesh
    ['tile-low014']: THREE.Mesh
    ['tile-low015']: THREE.Mesh
    ['tile-low016']: THREE.Mesh
    ['tile-low017']: THREE.Mesh
    ['tile-low068']: THREE.Mesh
    ['tile-low069']: THREE.Mesh
    ['tile-low070']: THREE.Mesh
    ['tile-low071']: THREE.Mesh
    ['tile-low072']: THREE.Mesh
    ['tile-low073']: THREE.Mesh
    ['tile-low074']: THREE.Mesh
    ['tile-low075']: THREE.Mesh
    ['tile-low076']: THREE.Mesh
    ['tile-low077']: THREE.Mesh
    ['tile-low078']: THREE.Mesh
    ['tile-low079']: THREE.Mesh
    ['tile-low080']: THREE.Mesh
    ['tile-low081']: THREE.Mesh
    ['tile-low082']: THREE.Mesh
    ['tile-low083']: THREE.Mesh
    ['tile-low084']: THREE.Mesh
    ['tile-low085']: THREE.Mesh
    ['tile-low086']: THREE.Mesh
    ['tile-low087']: THREE.Mesh
    ['tile-low104']: THREE.Mesh
    ['tile-low105']: THREE.Mesh
    ['tile-low106']: THREE.Mesh
    ['tile-low107']: THREE.Mesh
    ['tile-low108']: THREE.Mesh
    ['tile-low109']: THREE.Mesh
    ['tile-low110']: THREE.Mesh
    ['tile-low111']: THREE.Mesh
    ['tile-low112']: THREE.Mesh
    ['tile-low282']: THREE.Mesh
    ['tile-low113']: THREE.Mesh
    ['tile-low114']: THREE.Mesh
    ['tile-low115']: THREE.Mesh
    ['tile-low116']: THREE.Mesh
    ['tile-low117']: THREE.Mesh
    ['tile-low118']: THREE.Mesh
    ['tile-low119']: THREE.Mesh
    ['tile-low120']: THREE.Mesh
    ['tile-low121']: THREE.Mesh
    ['tile-low228']: THREE.Mesh
    ['tile-low229']: THREE.Mesh
    ['tile-low230']: THREE.Mesh
    ['tile-low312']: THREE.Mesh
    ['tile-low313']: THREE.Mesh
    ['tile-low314']: THREE.Mesh
    ['tile-low315']: THREE.Mesh
    ['tile-low316']: THREE.Mesh
    ['tile-low317']: THREE.Mesh
    ['tile-low324']: THREE.Mesh
    ['tile-low325']: THREE.Mesh
    ['tile-low169']: THREE.Mesh
    ['tile-low170']: THREE.Mesh
    ['tile-low172']: THREE.Mesh
    ['tile-low173']: THREE.Mesh
    ['tile-low174']: THREE.Mesh
    ['tile-low175']: THREE.Mesh
    ['tile-low176']: THREE.Mesh
    ['tile-low177']: THREE.Mesh
    ['tile-low178']: THREE.Mesh
    ['tile-low179']: THREE.Mesh
    ['tile-low180']: THREE.Mesh
    ['tile-low181']: THREE.Mesh
    ['tile-low240']: THREE.Mesh
    ['tile-low241']: THREE.Mesh
    ['tile-low303']: THREE.Mesh
    ['tile-low182']: THREE.Mesh
    ['tile-low183']: THREE.Mesh
    ['tile-low184']: THREE.Mesh
    ['tile-low185']: THREE.Mesh
    ['tile-low186']: THREE.Mesh
    ['tile-low187']: THREE.Mesh
    ['tile-low188']: THREE.Mesh
    ['tile-low189']: THREE.Mesh
    ['tile-low190']: THREE.Mesh
    ['tile-low191']: THREE.Mesh
    ['tile-low192']: THREE.Mesh
    ['tile-low193']: THREE.Mesh
    ['tile-low194']: THREE.Mesh
    ['tile-low195']: THREE.Mesh
    ['tile-low196']: THREE.Mesh
    ['tile-low242']: THREE.Mesh
    ['tile-low197']: THREE.Mesh
    ['tile-low198']: THREE.Mesh
    ['tile-low199']: THREE.Mesh
    ['tile-low200']: THREE.Mesh
    ['tile-low201']: THREE.Mesh
    ['tile-low202']: THREE.Mesh
    ['tile-low203']: THREE.Mesh
    ['tile-low204']: THREE.Mesh
    ['tile-low205']: THREE.Mesh
    ['tile-low206']: THREE.Mesh
    ['tile-low207']: THREE.Mesh
    ['tile-low208']: THREE.Mesh
    ['tile-low209']: THREE.Mesh
    ['tile-low210']: THREE.Mesh
    ['tile-low211']: THREE.Mesh
    ['tile-low213']: THREE.Mesh
    ['tile-low243']: THREE.Mesh
    ['tile-low304']: THREE.Mesh
    ['tile-low305']: THREE.Mesh
    ['tile-low306']: THREE.Mesh
    ['tile-low212']: THREE.Mesh
    ['tile-low214']: THREE.Mesh
    ['tile-low215']: THREE.Mesh
    ['tile-low216']: THREE.Mesh
    ['tile-low217']: THREE.Mesh
    ['tile-low218']: THREE.Mesh
    ['tile-low219']: THREE.Mesh
    ['tile-low220']: THREE.Mesh
    ['tile-low221']: THREE.Mesh
    ['tile-low222']: THREE.Mesh
    ['tile-low223']: THREE.Mesh
    ['tile-low224']: THREE.Mesh
    ['tile-low225']: THREE.Mesh
    ['tile-low226']: THREE.Mesh
    ['tile-low264']: THREE.Mesh
    ['tile-low265']: THREE.Mesh
    ['tile-low266']: THREE.Mesh
    ['tile-low273']: THREE.Mesh
    ['tile-low274']: THREE.Mesh
    ['tile-low275']: THREE.Mesh
    ['tile-low276']: THREE.Mesh
    ['tile-low278']: THREE.Mesh
    ['tile-low280']: THREE.Mesh
    ['tile-low281']: THREE.Mesh
    ['tile-low318']: THREE.Mesh
    ['tile-low319']: THREE.Mesh
    ['tile-low320']: THREE.Mesh
    ['tile-low283']: THREE.Mesh
    ['tile-low284']: THREE.Mesh
    ['tile-low285']: THREE.Mesh
    ['tile-low286']: THREE.Mesh
    ['tile-low287']: THREE.Mesh
    ['tile-low288']: THREE.Mesh
    ['tile-low289']: THREE.Mesh
    ['tile-low290']: THREE.Mesh
    ['tile-low291']: THREE.Mesh
    ['tile-low292']: THREE.Mesh
    ['tile-low293']: THREE.Mesh
    ['tile-low294']: THREE.Mesh
    ['tile-low295']: THREE.Mesh
    ['tile-low296']: THREE.Mesh
    ['tile-low297']: THREE.Mesh
    ['tile-low298']: THREE.Mesh
    ['tile-low001']: THREE.Mesh
    ['tile-low002']: THREE.Mesh
  }
  materials: {
    ['colormap.029']: THREE.MeshStandardMaterial
    ['colormap.030']: THREE.MeshStandardMaterial
    ['colormap.051']: THREE.MeshStandardMaterial
    ['colormap.052']: THREE.MeshStandardMaterial
    ['colormap.053']: THREE.MeshStandardMaterial
    ['colormap.054']: THREE.MeshStandardMaterial
    ['colormap.055']: THREE.MeshStandardMaterial
    ['colormap.047']: THREE.MeshStandardMaterial
    ['colormap.046']: THREE.MeshStandardMaterial
    ['colormap.048']: THREE.MeshStandardMaterial
    ['colormap.009']: THREE.MeshStandardMaterial
    ['colormap.010']: THREE.MeshStandardMaterial
    ['colormap.011']: THREE.MeshStandardMaterial
    ['colormap.024']: THREE.MeshStandardMaterial
    ['colormap.022']: THREE.MeshStandardMaterial
    ['colormap.021']: THREE.MeshStandardMaterial
    ['colormap.043']: THREE.MeshStandardMaterial
    ['colormap.042']: THREE.MeshStandardMaterial
    ['colormap.026']: THREE.MeshStandardMaterial
    ['colormap.023']: THREE.MeshStandardMaterial
    ['colormap.040']: THREE.MeshStandardMaterial
    ['colormap.020']: THREE.MeshStandardMaterial
    ['colormap.041']: THREE.MeshStandardMaterial
    ['colormap.025']: THREE.MeshStandardMaterial
    farm: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/tutorial_01.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <group name="INT_NE" position={[4.5, 0, -4.5]} userData={{ name: 'INT_NE', north: 'INT_NNE', south: 'INT_S', east: 'PathNode_top_right', west: 'INT_N' }} />
        <group name="INT_NW" position={[-3.5, 0, -4.5]} userData={{ name: 'INT_NW', north: 'INT_NNW', south: 'INT_WW', east: 'INT_N', west: 'INT_NWW' }} />
        <group name="INT_N" position={[0.5, 0, -4.5]} userData={{ name: 'INT_N', north: 'INT_NN', south: 'INT_W', east: 'INT_NE', west: 'INT_NW' }} />
        <group name="INT_WW" position={[-3.5, 0, -0.5]} userData={{ name: 'INT_WW', north: 'INT_NW', south: 'INT_SSW', east: 'INT_W', west: '' }} />
        <group name="INT_NNW" position={[-3.5, 0, -6.5]} userData={{ name: 'INT_NNW', north: '', south: 'INT_NW', east: '', west: '' }} />
        <group name="INT_NN" position={[0.5, 0, -7.5]} userData={{ name: 'INT_NN', north: '', south: 'INT_N', east: '', west: '' }} />
        <group name="INT_NNE" position={[4.5, 0, -6.5]} userData={{ name: 'INT_NNE', north: '', south: 'INT_NE', east: '', west: '' }} />
        <group name="INT_SSE" position={[7.5, 0, 1.5]} userData={{ name: 'INT_SSE', north: 'INT_SE', south: '', east: '', west: '' }} />
        <group name="INT_SW" position={[0.5, 0, 2.5]} userData={{ name: 'INT_SW', north: 'INT_W', south: '', east: '', west: '' }} />
        <group name="INT_SS" position={[4.5, 0, 1.5]} userData={{ name: 'INT_SS', north: 'INT_S', south: '', east: '', west: '' }} />
        <group name="INT_SSW" position={[-3.5, 0, 1.5]} userData={{ name: 'INT_SSW', north: 'INT_WW', south: '', east: '', west: '' }} />
        <group name="INT_NWW" position={[-5.5, 0, -4.5]} userData={{ name: 'INT_NWW', north: '', south: '', east: 'INT_NW', west: '' }} />
        <group name="INT_E" position={[10.5, 0, -0.5]} userData={{ name: 'INT_E', north: '', south: '', east: '', west: 'INT_SE' }} />
        <group name="INT_SE" position={[7.5, 0, -0.5]} userData={{ name: 'INT_SE', north: 'PathNode_top_right', south: 'INT_SSE', east: 'INT_E', west: 'INT_S' }} />
        <group name="INT_S" position={[4.5, 0, -0.5]} userData={{ name: 'INT_S', north: 'INT_NE', south: 'INT_SS', east: 'INT_SE', west: 'INT_W' }} />
        <group name="INT_W" position={[0.5, 0, -0.5]} userData={{ name: 'INT_W', north: 'INT_N', south: 'INT_SW', east: 'INT_S', west: 'INT_WW' }} />
        <group name="PathNode_top_right" position={[7.5, 0, -4.5]} userData={{ name: 'PathNode_top_right', north: '', south: 'INT_SE', east: '', west: 'INT_NE' }} />
        <group name="Pickup_House_01" position={[4.5, 0, -2.5]} userData={{ name: 'Pickup_House_01' }} />
        <group name="Pickup_House_01009" position={[3.5, 0, -4.5]} userData={{ name: 'Pickup_House_01.009' }} />
        <group name="Pickup_House_01020" position={[0.5, 0, 1.5]} userData={{ name: 'Pickup_House_01.020' }} />
        <group name="Pickup_House_01030" position={[0.5, 0, -2.5]} userData={{ name: 'Pickup_House_01.030' }} />
        <group name="Pickup_House_01034" position={[0.5, 0, -6.5]} userData={{ name: 'Pickup_House_01.034' }} />
        <group name="Pickup_House_01015" position={[-1.5, 0, -4.5]} userData={{ name: 'Pickup_House_01.015' }} />
        <group name="Pickup_House_01001" position={[0.5, 0, -3.5]} userData={{ name: 'Pickup_House_01.001' }} />
        <group name="Pickup_House_01002" position={[4.5, 0, -3.5]} userData={{ name: 'Pickup_House_01.002' }} />
        <group name="Pickup_House_01003" position={[6.5, 0, -4.5]} userData={{ name: 'Pickup_House_01.003' }} />
        <mesh name="tree-large" geometry={nodes['tree-large'].geometry} material={materials['colormap.029']} position={[2.8, 0, -1.3]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tree-large' }} />
        <mesh name="tree-large001" geometry={nodes['tree-large001'].geometry} material={materials['colormap.029']} position={[3, 0, -1.6]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tree-large.001' }} />
        <mesh name="tree-small" geometry={nodes['tree-small'].geometry} material={materials['colormap.030']} position={[3.2, 0, -1.2]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tree-small' }} />
        <mesh name="tree-small001" geometry={nodes['tree-small001'].geometry} material={materials['colormap.030']} position={[2.8, 0, -1.7]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tree-small.001' }} />
        <mesh name="tree-large002" geometry={nodes['tree-large002'].geometry} material={materials['colormap.029']} position={[6.8, 0, -1.3]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tree-large.002' }} />
        <mesh name="tree-small003" geometry={nodes['tree-small003'].geometry} material={materials['colormap.030']} position={[6.8, 0, -1.7]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tree-small.003' }} />
        <mesh name="road-end001" geometry={nodes['road-end001'].geometry} material={materials['colormap.051']} position={[7.5, 0, 1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-end.001' }} />
        <mesh name="road-end002" geometry={nodes['road-end002'].geometry} material={materials['colormap.051']} position={[0.5, 0, 2.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-end.002' }} />
        <mesh name="road-end003" geometry={nodes['road-end003'].geometry} material={materials['colormap.051']} position={[4.5, 0, 1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-end.003' }} />
        <mesh name="road-end004" geometry={nodes['road-end004'].geometry} material={materials['colormap.051']} position={[10.5, 0, -0.5]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'road-end.004' }} />
        <mesh name="road-end005" geometry={nodes['road-end005'].geometry} material={materials['colormap.051']} position={[4.5, 0, -6.5]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'road-end.005' }} />
        <mesh name="road-end006" geometry={nodes['road-end006'].geometry} material={materials['colormap.051']} position={[-3.5, 0, -6.5]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'road-end.006' }} />
        <mesh name="road-straight" geometry={nodes['road-straight'].geometry} material={materials['colormap.052']} position={[-0.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight' }} />
        <mesh name="road-straight001" geometry={nodes['road-straight001'].geometry} material={materials['colormap.052']} position={[-1.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.001' }} />
        <mesh name="road-straight002" geometry={nodes['road-straight002'].geometry} material={materials['colormap.052']} position={[-2.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.002' }} />
        <mesh name="road-straight003" geometry={nodes['road-straight003'].geometry} material={materials['colormap.052']} position={[1.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.003' }} />
        <mesh name="road-straight004" geometry={nodes['road-straight004'].geometry} material={materials['colormap.052']} position={[2.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.004' }} />
        <mesh name="road-straight005" geometry={nodes['road-straight005'].geometry} material={materials['colormap.052']} position={[3.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.005' }} />
        <mesh name="road-straight006" geometry={nodes['road-straight006'].geometry} material={materials['colormap.052']} position={[5.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.006' }} />
        <mesh name="road-straight007" geometry={nodes['road-straight007'].geometry} material={materials['colormap.052']} position={[6.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.007' }} />
        <mesh name="road-straight008" geometry={nodes['road-straight008'].geometry} material={materials['colormap.052']} position={[6.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.008' }} />
        <mesh name="road-straight009" geometry={nodes['road-straight009'].geometry} material={materials['colormap.052']} position={[5.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.009' }} />
        <mesh name="road-straight010" geometry={nodes['road-straight010'].geometry} material={materials['colormap.052']} position={[3.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.010' }} />
        <mesh name="road-straight011" geometry={nodes['road-straight011'].geometry} material={materials['colormap.052']} position={[1.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.011' }} />
        <mesh name="road-straight012" geometry={nodes['road-straight012'].geometry} material={materials['colormap.052']} position={[2.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.012' }} />
        <mesh name="road-straight013" geometry={nodes['road-straight013'].geometry} material={materials['colormap.052']} position={[-0.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.013' }} />
        <mesh name="road-straight014" geometry={nodes['road-straight014'].geometry} material={materials['colormap.052']} position={[-2.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.014' }} />
        <mesh name="road-straight015" geometry={nodes['road-straight015'].geometry} material={materials['colormap.052']} position={[-1.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.015' }} />
        <mesh name="road-straight016" geometry={nodes['road-straight016'].geometry} material={materials['colormap.052']} position={[-4.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.016' }} />
        <mesh name="road-straight042" geometry={nodes['road-straight042'].geometry} material={materials['colormap.052']} position={[9.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.042' }} />
        <mesh name="road-straight043" geometry={nodes['road-straight043'].geometry} material={materials['colormap.052']} position={[8.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-straight.043' }} />
        <mesh name="road-straight056" geometry={nodes['road-straight056'].geometry} material={materials['colormap.052']} position={[7.5, 0, 0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.056' }} />
        <mesh name="road-straight061" geometry={nodes['road-straight061'].geometry} material={materials['colormap.052']} position={[-3.5, 0, 0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.061' }} />
        <mesh name="road-straight062" geometry={nodes['road-straight062'].geometry} material={materials['colormap.052']} position={[-3.5, 0, -1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.062' }} />
        <mesh name="road-straight063" geometry={nodes['road-straight063'].geometry} material={materials['colormap.052']} position={[-3.5, 0, -2.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.063' }} />
        <mesh name="road-straight064" geometry={nodes['road-straight064'].geometry} material={materials['colormap.052']} position={[-3.5, 0, -3.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.064' }} />
        <mesh name="road-straight065" geometry={nodes['road-straight065'].geometry} material={materials['colormap.052']} position={[0.5, 0, -3.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.065' }} />
        <mesh name="road-straight066" geometry={nodes['road-straight066'].geometry} material={materials['colormap.052']} position={[0.5, 0, -2.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.066' }} />
        <mesh name="road-straight067" geometry={nodes['road-straight067'].geometry} material={materials['colormap.052']} position={[0.5, 0, -1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.067' }} />
        <mesh name="road-straight068" geometry={nodes['road-straight068'].geometry} material={materials['colormap.052']} position={[4.5, 0, -1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.068' }} />
        <mesh name="road-straight069" geometry={nodes['road-straight069'].geometry} material={materials['colormap.052']} position={[4.5, 0, -2.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.069' }} />
        <mesh name="road-straight070" geometry={nodes['road-straight070'].geometry} material={materials['colormap.052']} position={[4.5, 0, -3.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.070' }} />
        <mesh name="road-straight071" geometry={nodes['road-straight071'].geometry} material={materials['colormap.052']} position={[7.5, 0, -3.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.071' }} />
        <mesh name="road-straight072" geometry={nodes['road-straight072'].geometry} material={materials['colormap.052']} position={[7.5, 0, -2.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.072' }} />
        <mesh name="road-straight073" geometry={nodes['road-straight073'].geometry} material={materials['colormap.052']} position={[7.5, 0, -1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.073' }} />
        <mesh name="road-straight095" geometry={nodes['road-straight095'].geometry} material={materials['colormap.052']} position={[0.5, 0, 0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.095' }} />
        <mesh name="road-straight096" geometry={nodes['road-straight096'].geometry} material={materials['colormap.052']} position={[0.5, 0, 1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.096' }} />
        <mesh name="road-straight097" geometry={nodes['road-straight097'].geometry} material={materials['colormap.052']} position={[4.5, 0, 0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.097' }} />
        <mesh name="road-straight098" geometry={nodes['road-straight098'].geometry} material={materials['colormap.052']} position={[-3.5, 0, -5.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.098' }} />
        <mesh name="road-intersection" geometry={nodes['road-intersection'].geometry} material={materials['colormap.053']} position={[-3.5, 0, -0.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-intersection' }} />
        <mesh name="road-crossroad" geometry={nodes['road-crossroad'].geometry} material={materials['colormap.054']} position={[0.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-crossroad' }} />
        <mesh name="road-crossroad005" geometry={nodes['road-crossroad005'].geometry} material={materials['colormap.054']} position={[0.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-crossroad.005' }} />
        <mesh name="road-straight099" geometry={nodes['road-straight099'].geometry} material={materials['colormap.052']} position={[4.5, 0, -5.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.099' }} />
        <mesh name="road-crossroad-line" geometry={nodes['road-crossroad-line'].geometry} material={materials['colormap.055']} position={[4.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-crossroad-line' }} />
        <mesh name="road-crossroad-line001" geometry={nodes['road-crossroad-line001'].geometry} material={materials['colormap.055']} position={[7.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-crossroad-line.001' }} />
        <mesh name="road-crossroad-line003" geometry={nodes['road-crossroad-line003'].geometry} material={materials['colormap.055']} position={[4.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-crossroad-line.003' }} />
        <mesh name="road-crossroad-line004" geometry={nodes['road-crossroad-line004'].geometry} material={materials['colormap.055']} position={[-3.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-crossroad-line.004' }} />
        <mesh name="road-end008" geometry={nodes['road-end008'].geometry} material={materials['colormap.051']} position={[0.5, 0, -7.5]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'road-end.008' }} />
        <mesh name="road-straight075" geometry={nodes['road-straight075'].geometry} material={materials['colormap.052']} position={[0.5, 0, -6.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.075' }} />
        <mesh name="road-straight094" geometry={nodes['road-straight094'].geometry} material={materials['colormap.052']} position={[0.5, 0, -5.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-straight.094' }} />
        <mesh name="road-bend-square" geometry={nodes['road-bend-square'].geometry} material={materials['colormap.047']} position={[7.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-bend-square' }} />
        <mesh name="road-end007" geometry={nodes['road-end007'].geometry} material={materials['colormap.051']} position={[-5.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'road-end.007' }} />
        <mesh name="road-end009" geometry={nodes['road-end009'].geometry} material={materials['colormap.051']} position={[-3.5, 0, 1.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'road-end.009' }} />
        <mesh name="suv" geometry={nodes.suv.geometry} material={materials['colormap.046']} position={[10.3, 0, -1.4]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.5} userData={{ name: 'suv' }} />
        <mesh name="suv001" geometry={nodes.suv001.geometry} material={materials['colormap.046']} position={[-6.4, 0, -5.9]} rotation={[Math.PI / 2, 0, 0.26]} scale={0.5} userData={{ name: 'suv.001' }} />
        <mesh name="tractor-shovel" geometry={nodes['tractor-shovel'].geometry} material={materials['colormap.048']} position={[-4, 0, -9]} rotation={[Math.PI / 2, 0, 0.661]} scale={0.5} userData={{ name: 'tractor-shovel' }} />
        <mesh name="building-type-a" geometry={nodes['building-type-a'].geometry} material={materials['colormap.009']} position={[-0.69, 0, -3.23]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-a' }} />
        <mesh name="building-type-b" geometry={nodes['building-type-b'].geometry} material={materials['colormap.010']} position={[-2.3, 0, -3]} rotation={[Math.PI / 2, 0, -1.547]} userData={{ name: 'building-type-b' }} />
        <mesh name="building-type-l" geometry={nodes['building-type-l'].geometry} material={materials['colormap.011']} position={[-0.7, 0, -1.7]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-l' }} />
        <mesh name="building-type-a002" geometry={nodes['building-type-a002'].geometry} material={materials['colormap.024']} position={[-4.69, 0, -3.23]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-a.002' }} />
        <mesh name="building-type-b001" geometry={nodes['building-type-b001'].geometry} material={materials['colormap.022']} position={[-6.3, 0, -3]} rotation={[Math.PI / 2, 0, -1.547]} userData={{ name: 'building-type-b.001' }} />
        <mesh name="building-type-l001" geometry={nodes['building-type-l001'].geometry} material={materials['colormap.021']} position={[-4.7, 0, -1.7]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-l.001' }} />
        <mesh name="building-type-a003" geometry={nodes['building-type-a003'].geometry} material={materials['colormap.024']} position={[-4.69, 0, 0.37]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-a.003' }} />
        <mesh name="building-type-b002" geometry={nodes['building-type-b002'].geometry} material={materials['colormap.022']} position={[-6.3, 0, 0.5]} rotation={[Math.PI / 2, 0, -1.547]} userData={{ name: 'building-type-b.002' }} />
        <mesh name="building-type-l003" geometry={nodes['building-type-l003'].geometry} material={materials['colormap.021']} position={[-4.7, 0, 2.3]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-l.003' }} />
        <mesh name="building-type-a006" geometry={nodes['building-type-a006'].geometry} material={materials['colormap.043']} position={[-0.69, 0, 2.77]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-a.006' }} />
        <mesh name="building-type-b004" geometry={nodes['building-type-b004'].geometry} material={materials['colormap.042']} position={[-1.5, 0, 1.1]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'building-type-b.004' }} />
        <mesh name="building-type-b009" geometry={nodes['building-type-b009'].geometry} material={materials['colormap.022']} position={[-5.1, 0.2, -5.7]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'building-type-b.009' }} />
        <mesh name="building-type-a015" geometry={nodes['building-type-a015'].geometry} material={materials['colormap.024']} position={[-0.69, 0, -6.23]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'building-type-a.015' }} />
        <mesh name="building-type-b011" geometry={nodes['building-type-b011'].geometry} material={materials['colormap.022']} position={[-2.3, 0, -6]} rotation={[Math.PI / 2, 0, -1.547]} userData={{ name: 'building-type-b.011' }} />
        <mesh name="building-type-l010" geometry={nodes['building-type-l010'].geometry} material={materials['colormap.021']} position={[-0.7, 0, -7.7]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-l.010' }} />
        <mesh name="building-type-a001" geometry={nodes['building-type-a001'].geometry} material={materials['colormap.026']} position={[1.83, 0, -1.957]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'building-type-a.001' }} />
        <mesh name="building-type-c001" geometry={nodes['building-type-c001'].geometry} material={materials['colormap.023']} position={[3.04, 0, -3.187]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'building-type-c.001' }} />
        <mesh name="building-type-a004" geometry={nodes['building-type-a004'].geometry} material={materials['colormap.026']} position={[5.83, 0, -1.757]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'building-type-a.004' }} />
        <mesh name="building-type-c005" geometry={nodes['building-type-c005'].geometry} material={materials['colormap.023']} position={[6.04, 0, -3.187]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'building-type-c.005' }} />
        <mesh name="building-type-a005" geometry={nodes['building-type-a005'].geometry} material={materials['colormap.043']} position={[3.31, 0, 0.77]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-a.005' }} />
        <mesh name="building-type-b003" geometry={nodes['building-type-b003'].geometry} material={materials['colormap.042']} position={[1.7, 0, 1]} rotation={[Math.PI / 2, 0, -1.547]} userData={{ name: 'building-type-b.003' }} />
        <mesh name="building-type-l004" geometry={nodes['building-type-l004'].geometry} material={materials['colormap.040']} position={[3.3, 0, 2.3]} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'building-type-l.004' }} />
        <mesh name="building-type-b013" geometry={nodes['building-type-b013'].geometry} material={materials['colormap.022']} position={[1.7, 0, -6]} rotation={[Math.PI / 2, 0, -1.547]} userData={{ name: 'building-type-b.013' }} />
        <mesh name="building-type-c015" geometry={nodes['building-type-c015'].geometry} material={materials['colormap.020']} position={[1.7, 0, -7.5]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'building-type-c.015' }} />
        <mesh name="building-type-c017" geometry={nodes['building-type-c017'].geometry} material={materials['colormap.020']} position={[3.1, 0, -5.8]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'building-type-c.017' }} />
        <mesh name="building-type-a019" geometry={nodes['building-type-a019'].geometry} material={materials['colormap.024']} position={[7.11, 0, -6.23]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'building-type-a.019' }} />
        <mesh name="building-type-b015" geometry={nodes['building-type-b015'].geometry} material={materials['colormap.022']} position={[5.7, 0, -6]} rotation={[Math.PI / 2, 0, -1.547]} userData={{ name: 'building-type-b.015' }} />
        <mesh name="building-type-c016" geometry={nodes['building-type-c016'].geometry} material={materials['colormap.020']} position={[4.5, 0, -7.5]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'building-type-c.016' }} />
        <mesh name="building-type-c019" geometry={nodes['building-type-c019'].geometry} material={materials['colormap.041']} position={[8.8, 0, 0.7]} rotation={[Math.PI / 2, 0, -0.821]} userData={{ name: 'building-type-c.019' }} />
        <mesh name="building-type-l015" geometry={nodes['building-type-l015'].geometry} material={materials['colormap.040']} position={[5.5, 0, 2.6]} rotation={[Math.PI / 2, 0, -0.611]} userData={{ name: 'building-type-l.015' }} />
        <mesh name="building-type-b019" geometry={nodes['building-type-b019'].geometry} material={materials['colormap.042']} position={[8.7, 0, -4]} rotation={[Math.PI / 2, 0, -1.547]} userData={{ name: 'building-type-b.019' }} />
        <mesh name="building-type-c021" geometry={nodes['building-type-c021'].geometry} material={materials['colormap.041']} position={[8.7, 0, -2.5]} rotation={[Math.PI / 2, 0, Math.PI]} userData={{ name: 'building-type-c.021' }} />
        <mesh name="tile-low027" geometry={nodes['tile-low027'].geometry} material={materials['colormap.025']} position={[1.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.027' }} />
        <mesh name="tile-low028" geometry={nodes['tile-low028'].geometry} material={materials['colormap.025']} position={[2.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.028' }} />
        <mesh name="tile-low029" geometry={nodes['tile-low029'].geometry} material={materials['colormap.025']} position={[3.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.029' }} />
        <mesh name="tile-low030" geometry={nodes['tile-low030'].geometry} material={materials['colormap.025']} position={[1.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.030' }} />
        <mesh name="tile-low031" geometry={nodes['tile-low031'].geometry} material={materials['colormap.025']} position={[2.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.031' }} />
        <mesh name="tile-low032" geometry={nodes['tile-low032'].geometry} material={materials['colormap.025']} position={[3.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.032' }} />
        <mesh name="tile-low033" geometry={nodes['tile-low033'].geometry} material={materials['colormap.025']} position={[1.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.033' }} />
        <mesh name="tile-low034" geometry={nodes['tile-low034'].geometry} material={materials['colormap.025']} position={[2.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.034' }} />
        <mesh name="tile-low035" geometry={nodes['tile-low035'].geometry} material={materials['colormap.025']} position={[3.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.035' }} />
        <mesh name="tile-low089" geometry={nodes['tile-low089'].geometry} material={materials['colormap.025']} position={[6.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.089' }} />
        <mesh name="tile-low090" geometry={nodes['tile-low090'].geometry} material={materials['colormap.025']} position={[5.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.090' }} />
        <mesh name="tile-low092" geometry={nodes['tile-low092'].geometry} material={materials['colormap.025']} position={[6.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.092' }} />
        <mesh name="tile-low093" geometry={nodes['tile-low093'].geometry} material={materials['colormap.025']} position={[5.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.093' }} />
        <mesh name="tile-low095" geometry={nodes['tile-low095'].geometry} material={materials['colormap.025']} position={[6.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.095' }} />
        <mesh name="tile-low096" geometry={nodes['tile-low096'].geometry} material={materials['colormap.025']} position={[5.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.096' }} />
        <mesh name="tile-low009" geometry={nodes['tile-low009'].geometry} material={materials['colormap.025']} position={[-0.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.009' }} />
        <mesh name="tile-low010" geometry={nodes['tile-low010'].geometry} material={materials['colormap.025']} position={[-1.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.010' }} />
        <mesh name="tile-low011" geometry={nodes['tile-low011'].geometry} material={materials['colormap.025']} position={[-2.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.011' }} />
        <mesh name="tile-low012" geometry={nodes['tile-low012'].geometry} material={materials['colormap.025']} position={[-0.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.012' }} />
        <mesh name="tile-low013" geometry={nodes['tile-low013'].geometry} material={materials['colormap.025']} position={[-1.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.013' }} />
        <mesh name="tile-low014" geometry={nodes['tile-low014'].geometry} material={materials['colormap.025']} position={[-2.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.014' }} />
        <mesh name="tile-low015" geometry={nodes['tile-low015'].geometry} material={materials['colormap.025']} position={[-0.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.015' }} />
        <mesh name="tile-low016" geometry={nodes['tile-low016'].geometry} material={materials['colormap.025']} position={[-1.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.016' }} />
        <mesh name="tile-low017" geometry={nodes['tile-low017'].geometry} material={materials['colormap.025']} position={[-2.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.017' }} />
        <mesh name="tile-low068" geometry={nodes['tile-low068'].geometry} material={materials['colormap.025']} position={[-6.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.068' }} />
        <mesh name="tile-low069" geometry={nodes['tile-low069'].geometry} material={materials['colormap.025']} position={[-5.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.069' }} />
        <mesh name="tile-low070" geometry={nodes['tile-low070'].geometry} material={materials['colormap.025']} position={[-4.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.070' }} />
        <mesh name="tile-low071" geometry={nodes['tile-low071'].geometry} material={materials['colormap.025']} position={[-6.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.071' }} />
        <mesh name="tile-low072" geometry={nodes['tile-low072'].geometry} material={materials['colormap.025']} position={[-5.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.072' }} />
        <mesh name="tile-low073" geometry={nodes['tile-low073'].geometry} material={materials['colormap.025']} position={[-4.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.073' }} />
        <mesh name="tile-low074" geometry={nodes['tile-low074'].geometry} material={materials['colormap.025']} position={[-6.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.074' }} />
        <mesh name="tile-low075" geometry={nodes['tile-low075'].geometry} material={materials['colormap.025']} position={[-5.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.075' }} />
        <mesh name="tile-low076" geometry={nodes['tile-low076'].geometry} material={materials['colormap.025']} position={[-4.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.076' }} />
        <mesh name="tile-low077" geometry={nodes['tile-low077'].geometry} material={materials['colormap.025']} position={[-5.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.077' }} />
        <mesh name="tile-low078" geometry={nodes['tile-low078'].geometry} material={materials['colormap.025']} position={[-6.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.078' }} />
        <mesh name="tile-low079" geometry={nodes['tile-low079'].geometry} material={materials['colormap.025']} position={[-4.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.079' }} />
        <mesh name="tile-low080" geometry={nodes['tile-low080'].geometry} material={materials['colormap.025']} position={[-5.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.080' }} />
        <mesh name="tile-low081" geometry={nodes['tile-low081'].geometry} material={materials['colormap.025']} position={[-6.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.081' }} />
        <mesh name="tile-low082" geometry={nodes['tile-low082'].geometry} material={materials['colormap.025']} position={[-4.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.082' }} />
        <mesh name="tile-low083" geometry={nodes['tile-low083'].geometry} material={materials['colormap.025']} position={[-5.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.083' }} />
        <mesh name="tile-low084" geometry={nodes['tile-low084'].geometry} material={materials['colormap.025']} position={[-6.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.084' }} />
        <mesh name="tile-low085" geometry={nodes['tile-low085'].geometry} material={materials['colormap.025']} position={[-4.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.085' }} />
        <mesh name="tile-low086" geometry={nodes['tile-low086'].geometry} material={materials['colormap.025']} position={[-4.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.086' }} />
        <mesh name="tile-low087" geometry={nodes['tile-low087'].geometry} material={materials['colormap.025']} position={[-5.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.087' }} />
        <mesh name="tile-low104" geometry={nodes['tile-low104'].geometry} material={materials['colormap.025']} position={[1.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.104' }} />
        <mesh name="tile-low105" geometry={nodes['tile-low105'].geometry} material={materials['colormap.025']} position={[2.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.105' }} />
        <mesh name="tile-low106" geometry={nodes['tile-low106'].geometry} material={materials['colormap.025']} position={[3.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.106' }} />
        <mesh name="tile-low107" geometry={nodes['tile-low107'].geometry} material={materials['colormap.025']} position={[1.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.107' }} />
        <mesh name="tile-low108" geometry={nodes['tile-low108'].geometry} material={materials['colormap.025']} position={[2.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.108' }} />
        <mesh name="tile-low109" geometry={nodes['tile-low109'].geometry} material={materials['colormap.025']} position={[3.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.109' }} />
        <mesh name="tile-low110" geometry={nodes['tile-low110'].geometry} material={materials['colormap.025']} position={[1.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.110' }} />
        <mesh name="tile-low111" geometry={nodes['tile-low111'].geometry} material={materials['colormap.025']} position={[2.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.111' }} />
        <mesh name="tile-low112" geometry={nodes['tile-low112'].geometry} material={materials['colormap.025']} position={[3.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.112' }} />
        <mesh name="tile-low282" geometry={nodes['tile-low282'].geometry} material={materials['colormap.025']} position={[4.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.282' }} />
        <mesh name="tile-low113" geometry={nodes['tile-low113'].geometry} material={materials['colormap.025']} position={[-2.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.113' }} />
        <mesh name="tile-low114" geometry={nodes['tile-low114'].geometry} material={materials['colormap.025']} position={[-1.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.114' }} />
        <mesh name="tile-low115" geometry={nodes['tile-low115'].geometry} material={materials['colormap.025']} position={[-0.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.115' }} />
        <mesh name="tile-low116" geometry={nodes['tile-low116'].geometry} material={materials['colormap.025']} position={[-2.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.116' }} />
        <mesh name="tile-low117" geometry={nodes['tile-low117'].geometry} material={materials['colormap.025']} position={[-1.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.117' }} />
        <mesh name="tile-low118" geometry={nodes['tile-low118'].geometry} material={materials['colormap.025']} position={[-0.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.118' }} />
        <mesh name="tile-low119" geometry={nodes['tile-low119'].geometry} material={materials['colormap.025']} position={[-2.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.119' }} />
        <mesh name="tile-low120" geometry={nodes['tile-low120'].geometry} material={materials['colormap.025']} position={[-1.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.120' }} />
        <mesh name="tile-low121" geometry={nodes['tile-low121'].geometry} material={materials['colormap.025']} position={[-0.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.121' }} />
        <mesh name="tile-low228" geometry={nodes['tile-low228'].geometry} material={materials['colormap.025']} position={[-0.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.228' }} />
        <mesh name="tile-low229" geometry={nodes['tile-low229'].geometry} material={materials['colormap.025']} position={[0.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.229' }} />
        <mesh name="tile-low230" geometry={nodes['tile-low230'].geometry} material={materials['colormap.025']} position={[1.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.230' }} />
        <mesh name="tile-low312" geometry={nodes['tile-low312'].geometry} material={materials['colormap.025']} position={[2.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.312' }} />
        <mesh name="tile-low313" geometry={nodes['tile-low313'].geometry} material={materials['colormap.025']} position={[3.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.313' }} />
        <mesh name="tile-low314" geometry={nodes['tile-low314'].geometry} material={materials['colormap.025']} position={[4.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.314' }} />
        <mesh name="tile-low315" geometry={nodes['tile-low315'].geometry} material={materials['colormap.025']} position={[5.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.315' }} />
        <mesh name="tile-low316" geometry={nodes['tile-low316'].geometry} material={materials['colormap.025']} position={[6.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.316' }} />
        <mesh name="tile-low317" geometry={nodes['tile-low317'].geometry} material={materials['colormap.025']} position={[7.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.317' }} />
        <mesh name="tile-low324" geometry={nodes['tile-low324'].geometry} material={materials['colormap.025']} position={[-2.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.324' }} />
        <mesh name="tile-low325" geometry={nodes['tile-low325'].geometry} material={materials['colormap.025']} position={[-1.5, 0, 3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.325' }} />
        <mesh name="tile-low169" geometry={nodes['tile-low169'].geometry} material={materials.farm} position={[-4.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.169' }} />
        <mesh name="tile-low170" geometry={nodes['tile-low170'].geometry} material={materials.farm} position={[-5.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.170' }} />
        <mesh name="tile-low172" geometry={nodes['tile-low172'].geometry} material={materials.farm} position={[-4.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.172' }} />
        <mesh name="tile-low173" geometry={nodes['tile-low173'].geometry} material={materials.farm} position={[-5.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.173' }} />
        <mesh name="tile-low174" geometry={nodes['tile-low174'].geometry} material={materials.farm} position={[-6.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.174' }} />
        <mesh name="tile-low175" geometry={nodes['tile-low175'].geometry} material={materials.farm} position={[-4.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.175' }} />
        <mesh name="tile-low176" geometry={nodes['tile-low176'].geometry} material={materials['colormap.025']} position={[-5.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.176' }} />
        <mesh name="tile-low177" geometry={nodes['tile-low177'].geometry} material={materials['colormap.025']} position={[-6.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.177' }} />
        <mesh name="tile-low178" geometry={nodes['tile-low178'].geometry} material={materials['colormap.025']} position={[-4.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.178' }} />
        <mesh name="tile-low179" geometry={nodes['tile-low179'].geometry} material={materials['colormap.025']} position={[-5.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.179' }} />
        <mesh name="tile-low180" geometry={nodes['tile-low180'].geometry} material={materials['colormap.025']} position={[-4.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.180' }} />
        <mesh name="tile-low181" geometry={nodes['tile-low181'].geometry} material={materials['colormap.025']} position={[-6.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.181' }} />
        <mesh name="tile-low240" geometry={nodes['tile-low240'].geometry} material={materials['colormap.025']} position={[-3.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.240' }} />
        <mesh name="tile-low241" geometry={nodes['tile-low241'].geometry} material={materials['colormap.025']} position={[-3.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.241' }} />
        <mesh name="tile-low303" geometry={nodes['tile-low303'].geometry} material={materials['colormap.025']} position={[-3.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.303' }} />
        <mesh name="tile-low182" geometry={nodes['tile-low182'].geometry} material={materials['colormap.025']} position={[-1.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.182' }} />
        <mesh name="tile-low183" geometry={nodes['tile-low183'].geometry} material={materials['colormap.025']} position={[-2.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.183' }} />
        <mesh name="tile-low184" geometry={nodes['tile-low184'].geometry} material={materials['colormap.025']} position={[-0.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.184' }} />
        <mesh name="tile-low185" geometry={nodes['tile-low185'].geometry} material={materials['colormap.025']} position={[-1.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.185' }} />
        <mesh name="tile-low186" geometry={nodes['tile-low186'].geometry} material={materials['colormap.025']} position={[-2.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.186' }} />
        <mesh name="tile-low187" geometry={nodes['tile-low187'].geometry} material={materials['colormap.025']} position={[-0.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.187' }} />
        <mesh name="tile-low188" geometry={nodes['tile-low188'].geometry} material={materials['colormap.025']} position={[-1.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.188' }} />
        <mesh name="tile-low189" geometry={nodes['tile-low189'].geometry} material={materials['colormap.025']} position={[-2.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.189' }} />
        <mesh name="tile-low190" geometry={nodes['tile-low190'].geometry} material={materials['colormap.025']} position={[-0.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.190' }} />
        <mesh name="tile-low191" geometry={nodes['tile-low191'].geometry} material={materials['colormap.025']} position={[-1.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.191' }} />
        <mesh name="tile-low192" geometry={nodes['tile-low192'].geometry} material={materials['colormap.025']} position={[-2.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.192' }} />
        <mesh name="tile-low193" geometry={nodes['tile-low193'].geometry} material={materials['colormap.025']} position={[-0.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.193' }} />
        <mesh name="tile-low194" geometry={nodes['tile-low194'].geometry} material={materials['colormap.025']} position={[-1.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.194' }} />
        <mesh name="tile-low195" geometry={nodes['tile-low195'].geometry} material={materials['colormap.025']} position={[-0.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.195' }} />
        <mesh name="tile-low196" geometry={nodes['tile-low196'].geometry} material={materials['colormap.025']} position={[-2.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.196' }} />
        <mesh name="tile-low242" geometry={nodes['tile-low242'].geometry} material={materials['colormap.025']} position={[0.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.242' }} />
        <mesh name="tile-low197" geometry={nodes['tile-low197'].geometry} material={materials['colormap.025']} position={[2.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.197' }} />
        <mesh name="tile-low198" geometry={nodes['tile-low198'].geometry} material={materials['colormap.025']} position={[1.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.198' }} />
        <mesh name="tile-low199" geometry={nodes['tile-low199'].geometry} material={materials['colormap.025']} position={[3.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.199' }} />
        <mesh name="tile-low200" geometry={nodes['tile-low200'].geometry} material={materials['colormap.025']} position={[2.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.200' }} />
        <mesh name="tile-low201" geometry={nodes['tile-low201'].geometry} material={materials['colormap.025']} position={[1.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.201' }} />
        <mesh name="tile-low202" geometry={nodes['tile-low202'].geometry} material={materials['colormap.025']} position={[3.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.202' }} />
        <mesh name="tile-low203" geometry={nodes['tile-low203'].geometry} material={materials['colormap.025']} position={[2.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.203' }} />
        <mesh name="tile-low204" geometry={nodes['tile-low204'].geometry} material={materials['colormap.025']} position={[1.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.204' }} />
        <mesh name="tile-low205" geometry={nodes['tile-low205'].geometry} material={materials['colormap.025']} position={[4.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.205' }} />
        <mesh name="tile-low206" geometry={nodes['tile-low206'].geometry} material={materials['colormap.025']} position={[2.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.206' }} />
        <mesh name="tile-low207" geometry={nodes['tile-low207'].geometry} material={materials['colormap.025']} position={[1.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.207' }} />
        <mesh name="tile-low208" geometry={nodes['tile-low208'].geometry} material={materials['colormap.025']} position={[3.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.208' }} />
        <mesh name="tile-low209" geometry={nodes['tile-low209'].geometry} material={materials['colormap.025']} position={[2.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.209' }} />
        <mesh name="tile-low210" geometry={nodes['tile-low210'].geometry} material={materials['colormap.025']} position={[3.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.210' }} />
        <mesh name="tile-low211" geometry={nodes['tile-low211'].geometry} material={materials['colormap.025']} position={[1.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.211' }} />
        <mesh name="tile-low213" geometry={nodes['tile-low213'].geometry} material={materials['colormap.025']} position={[0.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.213' }} />
        <mesh name="tile-low243" geometry={nodes['tile-low243'].geometry} material={materials['colormap.025']} position={[4.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.243' }} />
        <mesh name="tile-low304" geometry={nodes['tile-low304'].geometry} material={materials['colormap.025']} position={[3.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.304' }} />
        <mesh name="tile-low305" geometry={nodes['tile-low305'].geometry} material={materials['colormap.025']} position={[4.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.305' }} />
        <mesh name="tile-low306" geometry={nodes['tile-low306'].geometry} material={materials['colormap.025']} position={[5.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.306' }} />
        <mesh name="tile-low212" geometry={nodes['tile-low212'].geometry} material={materials['colormap.025']} position={[6.5, 0, -9.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.212' }} />
        <mesh name="tile-low214" geometry={nodes['tile-low214'].geometry} material={materials['colormap.025']} position={[7.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.214' }} />
        <mesh name="tile-low215" geometry={nodes['tile-low215'].geometry} material={materials['colormap.025']} position={[6.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.215' }} />
        <mesh name="tile-low216" geometry={nodes['tile-low216'].geometry} material={materials['colormap.025']} position={[5.5, 0, -8.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.216' }} />
        <mesh name="tile-low217" geometry={nodes['tile-low217'].geometry} material={materials['colormap.025']} position={[7.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.217' }} />
        <mesh name="tile-low218" geometry={nodes['tile-low218'].geometry} material={materials['colormap.025']} position={[6.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.218' }} />
        <mesh name="tile-low219" geometry={nodes['tile-low219'].geometry} material={materials['colormap.025']} position={[5.5, 0, -7.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.219' }} />
        <mesh name="tile-low220" geometry={nodes['tile-low220'].geometry} material={materials['colormap.025']} position={[8.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.220' }} />
        <mesh name="tile-low221" geometry={nodes['tile-low221'].geometry} material={materials['colormap.025']} position={[6.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.221' }} />
        <mesh name="tile-low222" geometry={nodes['tile-low222'].geometry} material={materials['colormap.025']} position={[5.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.222' }} />
        <mesh name="tile-low223" geometry={nodes['tile-low223'].geometry} material={materials['colormap.025']} position={[7.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.223' }} />
        <mesh name="tile-low224" geometry={nodes['tile-low224'].geometry} material={materials['colormap.025']} position={[6.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.224' }} />
        <mesh name="tile-low225" geometry={nodes['tile-low225'].geometry} material={materials['colormap.025']} position={[7.5, 0, -6.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.225' }} />
        <mesh name="tile-low226" geometry={nodes['tile-low226'].geometry} material={materials['colormap.025']} position={[5.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.226' }} />
        <mesh name="tile-low264" geometry={nodes['tile-low264'].geometry} material={materials['colormap.025']} position={[8.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.264' }} />
        <mesh name="tile-low265" geometry={nodes['tile-low265'].geometry} material={materials['colormap.025']} position={[9.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.265' }} />
        <mesh name="tile-low266" geometry={nodes['tile-low266'].geometry} material={materials['colormap.025']} position={[10.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.266' }} />
        <mesh name="tile-low273" geometry={nodes['tile-low273'].geometry} material={materials['colormap.025']} position={[5.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.273' }} />
        <mesh name="tile-low274" geometry={nodes['tile-low274'].geometry} material={materials['colormap.025']} position={[6.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.274' }} />
        <mesh name="tile-low275" geometry={nodes['tile-low275'].geometry} material={materials['colormap.025']} position={[7.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.275' }} />
        <mesh name="tile-low276" geometry={nodes['tile-low276'].geometry} material={materials['colormap.025']} position={[6.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.276' }} />
        <mesh name="tile-low278" geometry={nodes['tile-low278'].geometry} material={materials['colormap.025']} position={[6.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.278' }} />
        <mesh name="tile-low280" geometry={nodes['tile-low280'].geometry} material={materials['colormap.025']} position={[5.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.280' }} />
        <mesh name="tile-low281" geometry={nodes['tile-low281'].geometry} material={materials['colormap.025']} position={[5.5, 0, 0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.281' }} />
        <mesh name="tile-low318" geometry={nodes['tile-low318'].geometry} material={materials['colormap.025']} position={[8.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.318' }} />
        <mesh name="tile-low319" geometry={nodes['tile-low319'].geometry} material={materials['colormap.025']} position={[8.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.319' }} />
        <mesh name="tile-low320" geometry={nodes['tile-low320'].geometry} material={materials['colormap.025']} position={[9.5, 0, 1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.320' }} />
        <mesh name="tile-low283" geometry={nodes['tile-low283'].geometry} material={materials['colormap.025']} position={[8.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.283' }} />
        <mesh name="tile-low284" geometry={nodes['tile-low284'].geometry} material={materials['colormap.025']} position={[9.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.284' }} />
        <mesh name="tile-low285" geometry={nodes['tile-low285'].geometry} material={materials['colormap.025']} position={[10.5, 0, -2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.285' }} />
        <mesh name="tile-low286" geometry={nodes['tile-low286'].geometry} material={materials['colormap.025']} position={[9.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.286' }} />
        <mesh name="tile-low287" geometry={nodes['tile-low287'].geometry} material={materials['colormap.025']} position={[10.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.287' }} />
        <mesh name="tile-low288" geometry={nodes['tile-low288'].geometry} material={materials['colormap.025']} position={[9.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.288' }} />
        <mesh name="tile-low289" geometry={nodes['tile-low289'].geometry} material={materials['colormap.025']} position={[10.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.289' }} />
        <mesh name="tile-low290" geometry={nodes['tile-low290'].geometry} material={materials['colormap.025']} position={[8.5, 0, -3.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.290' }} />
        <mesh name="tile-low291" geometry={nodes['tile-low291'].geometry} material={materials['colormap.025']} position={[8.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.291' }} />
        <mesh name="tile-low292" geometry={nodes['tile-low292'].geometry} material={materials['colormap.025']} position={[9.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.292' }} />
        <mesh name="tile-low293" geometry={nodes['tile-low293'].geometry} material={materials['colormap.025']} position={[10.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.293' }} />
        <mesh name="tile-low294" geometry={nodes['tile-low294'].geometry} material={materials['colormap.025']} position={[8.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.294' }} />
        <mesh name="tile-low295" geometry={nodes['tile-low295'].geometry} material={materials['colormap.025']} position={[9.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.295' }} />
        <mesh name="tile-low296" geometry={nodes['tile-low296'].geometry} material={materials['colormap.025']} position={[8.5, 0, -5.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.296' }} />
        <mesh name="tile-low297" geometry={nodes['tile-low297'].geometry} material={materials['colormap.025']} position={[11.5, 0, -0.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.297' }} />
        <mesh name="tile-low298" geometry={nodes['tile-low298'].geometry} material={materials['colormap.025']} position={[11.5, 0, -1.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.298' }} />
        <mesh name="tile-low001" geometry={nodes['tile-low001'].geometry} material={materials['colormap.025']} position={[-6.5, 0, -4.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.001' }} />
        <mesh name="tile-low002" geometry={nodes['tile-low002'].geometry} material={materials['colormap.025']} position={[-3.5, 0, 2.5]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'tile-low.002' }} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/tutorial_01.glb'))
