/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tutorial_01.glb --output generated_components/TutorialModelGenerated.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    SM_Env_Sidewalk_Dip_Corner_36022: THREE.Mesh
    SM_Env_Sidewalk_Dip_Corner_36023: THREE.Mesh
    SM_Env_Sidewalk_Straight_323037: THREE.Mesh
    SM_Env_Sidewalk_Straight_323038: THREE.Mesh
    Icosphere: THREE.Mesh
    Icosphere001: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere006: THREE.Mesh
    Icosphere007: THREE.Mesh
    Icosphere008: THREE.Mesh
    Icosphere009: THREE.Mesh
    Icosphere010: THREE.Mesh
    Icosphere011: THREE.Mesh
    Icosphere012: THREE.Mesh
    Icosphere013: THREE.Mesh
    Icosphere014: THREE.Mesh
    Cylinder: THREE.Mesh
    grass: THREE.Mesh
    Cylinder001: THREE.Mesh
    grass001: THREE.Mesh
    SM_Env_Road_Bare_99: THREE.Mesh
    SM_Env_Road_Bare_99001: THREE.Mesh
    SM_Env_Road_Bare_99002: THREE.Mesh
    SM_Env_Road_Bare_99003: THREE.Mesh
    SM_Env_Road_Bare_99004: THREE.Mesh
    SM_Env_Road_Bare_99005: THREE.Mesh
    SM_Env_Road_Bare_99006: THREE.Mesh
    SM_Env_Road_Bare_99007: THREE.Mesh
    SM_Env_Road_Bare_99011: THREE.Mesh
    SM_Env_Road_Bare_99012: THREE.Mesh
    SM_Env_Road_Bare_99013: THREE.Mesh
    SM_Env_Road_Bare_99014: THREE.Mesh
    SM_Env_Road_Bare_99015: THREE.Mesh
    SM_Env_Road_Bare_99016: THREE.Mesh
    SM_Env_Road_Bare_99017: THREE.Mesh
    SM_Env_Road_Bare_99018: THREE.Mesh
    SM_Env_Road_Bare_99019: THREE.Mesh
    SM_Env_Road_Bare_99066: THREE.Mesh
    SM_Env_Road_Bare_99067: THREE.Mesh
    SM_Env_Road_Bare_99068: THREE.Mesh
    SM_Env_Road_Bare_99069: THREE.Mesh
    SM_Env_Road_Bare_99070: THREE.Mesh
    SM_Env_Road_Bare_99071: THREE.Mesh
    SM_Env_Road_Bare_99088: THREE.Mesh
    SM_Env_Road_Bare_99091: THREE.Mesh
    SM_Env_Road_Bare_99095: THREE.Mesh
    SM_Env_Road_Bare_99099: THREE.Mesh
    SM_Env_Road_Bare_99100: THREE.Mesh
    SM_Env_Road_Bare_99101: THREE.Mesh
    SM_Env_Road_Bare_99102: THREE.Mesh
    SM_Env_Road_Bare_99103: THREE.Mesh
    SM_Env_Road_Bare_99104: THREE.Mesh
    SM_Env_Road_Bare_99105: THREE.Mesh
    SM_Env_Road_Bare_99107: THREE.Mesh
    SM_Env_Road_Bare_99109: THREE.Mesh
    SM_Env_Road_Bare_99110: THREE.Mesh
    SM_Env_Road_Bare_99118: THREE.Mesh
    SM_Env_Road_Bare_99119: THREE.Mesh
    SM_Env_Road_Bare_99072: THREE.Mesh
    SM_Env_Road_Bare_99073: THREE.Mesh
    SM_Env_Road_Bare_99060: THREE.Mesh
    SM_Env_Road_Bare_99061: THREE.Mesh
    SM_Env_Road_Bare_99021: THREE.Mesh
    SM_Env_Road_Bare_99022: THREE.Mesh
    SM_Env_Road_Bare_99023: THREE.Mesh
    SM_Env_Road_Bare_99024: THREE.Mesh
    SM_Env_Road_Bare_99025: THREE.Mesh
    SM_Env_Road_Bare_99026: THREE.Mesh
    SM_Env_Road_Bare_99027: THREE.Mesh
    SM_Env_Road_Bare_99028: THREE.Mesh
    SM_Env_Road_Bare_99029: THREE.Mesh
    SM_Env_Road_Bare_99030: THREE.Mesh
    SM_Env_Road_Bare_99031: THREE.Mesh
    SM_Env_Road_Bare_99032: THREE.Mesh
    SM_Env_Road_Bare_99033: THREE.Mesh
    SM_Env_Road_Bare_99034: THREE.Mesh
    SM_Env_Road_Bare_99035: THREE.Mesh
    SM_Env_Road_Bare_99036: THREE.Mesh
    SM_Env_Road_Bare_99037: THREE.Mesh
    SM_Env_Road_Bare_99038: THREE.Mesh
    SM_Env_Road_Bare_99039: THREE.Mesh
    SM_Env_Road_Bare_99040: THREE.Mesh
    SM_Env_Road_Bare_99041: THREE.Mesh
    SM_Env_Road_Bare_99042: THREE.Mesh
    trashcan005: THREE.Mesh
    SM_Prop_Manhole_29: THREE.Mesh
    SM_Prop_Manhole_29001: THREE.Mesh
    SM_Prop_Manhole_29009: THREE.Mesh
    SM_Prop_Manhole_29010: THREE.Mesh
    SM_Prop_Manhole_29011: THREE.Mesh
    SM_Prop_SidewalkPoles_08011: THREE.Mesh
    SM_Prop_SidewalkPoles_08012: THREE.Mesh
    SM_Prop_SidewalkPoles_08001: THREE.Mesh
    SM_Prop_SidewalkPoles_08002: THREE.Mesh
    trashcan001: THREE.Mesh
    trashcan002: THREE.Mesh
    trashcan003: THREE.Mesh
    park001: THREE.Mesh
  }
  materials: {
    Synty_Palette_A: THREE.MeshStandardMaterial
    grass: THREE.MeshStandardMaterial
    iron: THREE.MeshStandardMaterial
    ['dirt.001']: THREE.MeshStandardMaterial
    ['grass.001']: THREE.MeshStandardMaterial
    Road_01: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/tutorial_01.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <group name="INT_Main" position={[0.5, 0, -0.5]} userData={{ name: 'INT_Main', north: 'PathNode_N_01', south: 'StarterNode', east: 'PathNode_E_01', west: 'PathNode_W_01', ant_landscape: {} }} />
        <group name="PathNode_E_01" position={[5.5, 0, -0.5]} userData={{ name: 'PathNode_E_01', north: '', south: '', east: '', west: 'INT_Main', ant_landscape: {} }} />
        <group name="PathNode_W_01" position={[-4.5, 0, -0.5]} userData={{ name: 'PathNode_W_01', north: '', south: '', east: 'INT_Main', west: '', ant_landscape: {} }} />
        <group name="StarterNode" position={[0.5, 0, 1.5]} userData={{ name: 'StarterNode', north: 'INT_Main', south: '', east: '', west: '', ant_landscape: {} }} />
        <group name="PathNode_N_01" position={[0.5, 0, -2.5]} userData={{ name: 'PathNode_N_01', north: '', south: 'INT_Main', east: '', west: '', ant_landscape: {} }} />
        <group name="Pickup_House_01006" position={[-2.5, 0, -0.5]} userData={{ name: 'Pickup_House_01.006', ant_landscape: {} }} />
        <group name="Pickup_House_01001" position={[3.5, 0, -0.5]} userData={{ name: 'Pickup_House_01.001', ant_landscape: {} }} />
        <mesh name="SM_Env_Sidewalk_Dip_Corner_36022" geometry={nodes.SM_Env_Sidewalk_Dip_Corner_36022.geometry} material={materials.Synty_Palette_A} userData={{ name: 'SM_Env_Sidewalk_Dip_Corner_36.022' }} />
        <mesh name="SM_Env_Sidewalk_Dip_Corner_36023" geometry={nodes.SM_Env_Sidewalk_Dip_Corner_36023.geometry} material={materials.Synty_Palette_A} userData={{ name: 'SM_Env_Sidewalk_Dip_Corner_36.023' }} />
        <mesh name="SM_Env_Sidewalk_Straight_323037" geometry={nodes.SM_Env_Sidewalk_Straight_323037.geometry} material={materials.Synty_Palette_A} userData={{ name: 'SM_Env_Sidewalk_Straight_323.037' }} />
        <mesh name="SM_Env_Sidewalk_Straight_323038" geometry={nodes.SM_Env_Sidewalk_Straight_323038.geometry} material={materials.Synty_Palette_A} userData={{ name: 'SM_Env_Sidewalk_Straight_323.038', ant_landscape: {} }} />
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials.grass} position={[-2.725, -2.335, 16.253]} rotation={[0.398, -0.08, 0.497]} scale={[7.227, 4.824, 4.824]} userData={{ name: 'Icosphere', ant_landscape: {} }} />
        <mesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={materials.grass} position={[4.343, -2.625, 18.129]} rotation={[0, 0.432, 0]} scale={[4.63, 3.09, 3.09]} userData={{ name: 'Icosphere.001', ant_landscape: {} }} />
        <mesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} position={[-12.673, -7.358, 3.056]} rotation={[0, 0, 0.508]} scale={[2.744, 3.501, 3.267]} userData={{ name: 'Icosphere.002', ant_landscape: {} }} />
        <mesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={materials.iron} position={[6.55, -9.569, -2.045]} rotation={[0, 1.004, -0.345]} scale={[2.408, 3.072, 2.867]} userData={{ name: 'Icosphere.003', ant_landscape: {} }} />
        <mesh name="Icosphere006" geometry={nodes.Icosphere006.geometry} material={materials.grass} position={[-16.159, -3.291, 3.564]} rotation={[1.602, -0.508, 2.105]} scale={[6.928, 2.964, 4.342]} userData={{ name: 'Icosphere.006', ant_landscape: {} }} />
        <mesh name="Icosphere007" geometry={nodes.Icosphere007.geometry} material={materials.grass} position={[-14.3, -1.635, 15.178]} rotation={[0.898, -0.399, 0.679]} scale={[5.601, 2.396, 3.51]} userData={{ name: 'Icosphere.007', ant_landscape: {} }} />
        <mesh name="Icosphere008" geometry={nodes.Icosphere008.geometry} material={materials.grass} position={[11.454, -2.798, -7.189]} rotation={[2.294, 0.975, -2.013]} scale={[7.227, 4.824, 4.824]} userData={{ name: 'Icosphere.008', ant_landscape: {} }} />
        <mesh name="Icosphere009" geometry={nodes.Icosphere009.geometry} material={materials.grass} position={[16.523, -1.173, 3.169]} rotation={[1.433, 0.765, -1.275]} scale={[5.601, 2.396, 3.51]} userData={{ name: 'Icosphere.009', ant_landscape: {} }} />
        <mesh name="Icosphere010" geometry={nodes.Icosphere010.geometry} material={materials.grass} position={[12.724, -2.348, 12.274]} rotation={[1.111, 0.512, -0.566]} scale={[7.875, 3.103, 3.017]} userData={{ name: 'Icosphere.010', ant_landscape: {} }} />
        <mesh name="Icosphere011" geometry={nodes.Icosphere011.geometry} material={materials.grass} position={[-12.273, -3.062, -9.907]} rotation={[2.97, -0.452, -2.932]} scale={[7.227, 4.824, 4.824]} userData={{ name: 'Icosphere.011', ant_landscape: {} }} />
        <mesh name="Icosphere012" geometry={nodes.Icosphere012.geometry} material={materials.grass} position={[-2.144, -0.378, -14.989]} rotation={[2.631, 0.025, -2.947]} scale={[5.601, 2.396, 3.51]} userData={{ name: 'Icosphere.012', ant_landscape: {} }} />
        <mesh name="Icosphere013" geometry={nodes.Icosphere013.geometry} material={materials.grass} position={[7.089, -2.878, -12.3]} rotation={[2.429, 0.326, -2.397]} scale={[7.875, 3.103, 3.017]} userData={{ name: 'Icosphere.013', ant_landscape: {} }} />
        <mesh name="Icosphere014" geometry={nodes.Icosphere014.geometry} material={materials.grass} position={[-17.088, -1.635, -0.594]} rotation={[1.763, -0.857, 1.599]} scale={[5.601, 2.396, 3.51]} userData={{ name: 'Icosphere.014', ant_landscape: {} }} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['dirt.001']} position={[-0.984, -9.427, 2.993]} scale={[1.169, 0.776, 1.169]} userData={{ name: 'Cylinder', ant_landscape: {} }} />
        <mesh name="grass" geometry={nodes.grass.geometry} material={materials['grass.001']} userData={{ name: 'grass', ant_landscape: {} }} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['dirt.001']} position={[-0.984, -9.427, 1.993]} scale={[1.169, 0.776, 1.169]} userData={{ name: 'Cylinder.001', ant_landscape: {} }} />
        <mesh name="grass001" geometry={nodes.grass001.geometry} material={materials['grass.001']} position={[0, 0, -1]} userData={{ name: 'grass.001', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99" geometry={nodes.SM_Env_Road_Bare_99.geometry} material={materials.Road_01} position={[1, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99001" geometry={nodes.SM_Env_Road_Bare_99001.geometry} material={materials.Road_01} position={[2, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.001', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99002" geometry={nodes.SM_Env_Road_Bare_99002.geometry} material={materials.Road_01} position={[3, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.002', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99003" geometry={nodes.SM_Env_Road_Bare_99003.geometry} material={materials.Road_01} position={[4, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.003', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99004" geometry={nodes.SM_Env_Road_Bare_99004.geometry} material={materials.Road_01} position={[5, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.004', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99005" geometry={nodes.SM_Env_Road_Bare_99005.geometry} material={materials.Road_01} position={[6, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.005', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99006" geometry={nodes.SM_Env_Road_Bare_99006.geometry} material={materials.Road_01} position={[7, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.006', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99007" geometry={nodes.SM_Env_Road_Bare_99007.geometry} material={materials.Road_01} position={[8, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.007', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99011" geometry={nodes.SM_Env_Road_Bare_99011.geometry} material={materials.Road_01} position={[-1, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.011', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99012" geometry={nodes.SM_Env_Road_Bare_99012.geometry} material={materials.Road_01} position={[0, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.012', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99013" geometry={nodes.SM_Env_Road_Bare_99013.geometry} material={materials.Road_01} position={[1, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.013', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99014" geometry={nodes.SM_Env_Road_Bare_99014.geometry} material={materials.Road_01} position={[2, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.014', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99015" geometry={nodes.SM_Env_Road_Bare_99015.geometry} material={materials.Road_01} position={[3, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.015', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99016" geometry={nodes.SM_Env_Road_Bare_99016.geometry} material={materials.Road_01} position={[4, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.016', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99017" geometry={nodes.SM_Env_Road_Bare_99017.geometry} material={materials.Road_01} position={[5, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.017', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99018" geometry={nodes.SM_Env_Road_Bare_99018.geometry} material={materials.Road_01} position={[6, 0, -4]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.018', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99019" geometry={nodes.SM_Env_Road_Bare_99019.geometry} material={materials.Road_01} position={[7, 0, -4]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.019', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99066" geometry={nodes.SM_Env_Road_Bare_99066.geometry} material={materials.Road_01} position={[5, 0, -4]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.066', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99067" geometry={nodes.SM_Env_Road_Bare_99067.geometry} material={materials.Road_01} position={[5, 0, -3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.067', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99068" geometry={nodes.SM_Env_Road_Bare_99068.geometry} material={materials.Road_01} position={[5, 0, -2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.068', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99069" geometry={nodes.SM_Env_Road_Bare_99069.geometry} material={materials.Road_01} position={[8, 0, -4]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.069', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99070" geometry={nodes.SM_Env_Road_Bare_99070.geometry} material={materials.Road_01} position={[8, 0, -3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.070', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99071" geometry={nodes.SM_Env_Road_Bare_99071.geometry} material={materials.Road_01} position={[8, 0, -2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.071', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99088" geometry={nodes.SM_Env_Road_Bare_99088.geometry} material={materials.Road_01} position={[-3, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.088', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99091" geometry={nodes.SM_Env_Road_Bare_99091.geometry} material={materials.Road_01} position={[-2, 0, -5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.091', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99095" geometry={nodes.SM_Env_Road_Bare_99095.geometry} material={materials.Road_01} position={[-3, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.095', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99099" geometry={nodes.SM_Env_Road_Bare_99099.geometry} material={materials.Road_01} position={[-2, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.099', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99100" geometry={nodes.SM_Env_Road_Bare_99100.geometry} material={materials.Road_01} position={[-1, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.100', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99101" geometry={nodes.SM_Env_Road_Bare_99101.geometry} material={materials.Road_01} position={[0, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.101', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99102" geometry={nodes.SM_Env_Road_Bare_99102.geometry} material={materials.Road_01} position={[-6, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.102', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99103" geometry={nodes.SM_Env_Road_Bare_99103.geometry} material={materials.Road_01} position={[-6, 0, -3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.103', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99104" geometry={nodes.SM_Env_Road_Bare_99104.geometry} material={materials.Road_01} position={[-6, 0, -2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.104', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99105" geometry={nodes.SM_Env_Road_Bare_99105.geometry} material={materials.Road_01} position={[-7, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.105', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99107" geometry={nodes.SM_Env_Road_Bare_99107.geometry} material={materials.Road_01} position={[-7, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.107', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99109" geometry={nodes.SM_Env_Road_Bare_99109.geometry} material={materials.Road_01} position={[-7, 0, 1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.109', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99110" geometry={nodes.SM_Env_Road_Bare_99110.geometry} material={materials.Road_01} position={[-7, 0, 2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.110', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99118" geometry={nodes.SM_Env_Road_Bare_99118.geometry} material={materials.Road_01} position={[-5, 0, -3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.118', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99119" geometry={nodes.SM_Env_Road_Bare_99119.geometry} material={materials.Road_01} position={[-5, 0, -4]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.119', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99072" geometry={nodes.SM_Env_Road_Bare_99072.geometry} material={materials.Road_01} position={[1, 0, -2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.072', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99073" geometry={nodes.SM_Env_Road_Bare_99073.geometry} material={materials.Road_01} position={[1, 0, -3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.073', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99060" geometry={nodes.SM_Env_Road_Bare_99060.geometry} material={materials.Road_01} position={[1, 0, 1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.060', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99061" geometry={nodes.SM_Env_Road_Bare_99061.geometry} material={materials.Road_01} position={[1, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.061', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99021" geometry={nodes.SM_Env_Road_Bare_99021.geometry} material={materials.Road_01} position={[-4, 0, -1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.021', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99022" geometry={nodes.SM_Env_Road_Bare_99022.geometry} material={materials.Road_01} position={[-3, 0, -4]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.022', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99023" geometry={nodes.SM_Env_Road_Bare_99023.geometry} material={materials.Road_01} position={[-4, 0, -4]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.023', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99024" geometry={nodes.SM_Env_Road_Bare_99024.geometry} material={materials.Road_01} position={[-4, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.024', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99025" geometry={nodes.SM_Env_Road_Bare_99025.geometry} material={materials.Road_01} position={[-3, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.025', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99026" geometry={nodes.SM_Env_Road_Bare_99026.geometry} material={materials.Road_01} position={[-2, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.026', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99027" geometry={nodes.SM_Env_Road_Bare_99027.geometry} material={materials.Road_01} position={[-1, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.027', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99028" geometry={nodes.SM_Env_Road_Bare_99028.geometry} material={materials.Road_01} position={[0, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.028', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99029" geometry={nodes.SM_Env_Road_Bare_99029.geometry} material={materials.Road_01} position={[-6, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.029', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99030" geometry={nodes.SM_Env_Road_Bare_99030.geometry} material={materials.Road_01} position={[-5, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.030', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99031" geometry={nodes.SM_Env_Road_Bare_99031.geometry} material={materials.Road_01} position={[-7, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.031', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99032" geometry={nodes.SM_Env_Road_Bare_99032.geometry} material={materials.Road_01} position={[4, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.032', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99033" geometry={nodes.SM_Env_Road_Bare_99033.geometry} material={materials.Road_01} position={[5, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.033', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99034" geometry={nodes.SM_Env_Road_Bare_99034.geometry} material={materials.Road_01} position={[5, 0, 2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.034', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99035" geometry={nodes.SM_Env_Road_Bare_99035.geometry} material={materials.Road_01} position={[6, 0, 2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.035', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99036" geometry={nodes.SM_Env_Road_Bare_99036.geometry} material={materials.Road_01} position={[7, 0, 2]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.036', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99037" geometry={nodes.SM_Env_Road_Bare_99037.geometry} material={materials.Road_01} position={[2, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.037', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99038" geometry={nodes.SM_Env_Road_Bare_99038.geometry} material={materials.Road_01} position={[3, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.038', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99039" geometry={nodes.SM_Env_Road_Bare_99039.geometry} material={materials.Road_01} position={[1, 0, 3]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.039', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99040" geometry={nodes.SM_Env_Road_Bare_99040.geometry} material={materials.Road_01} position={[7, 0, 1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.040', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99041" geometry={nodes.SM_Env_Road_Bare_99041.geometry} material={materials.Road_01} position={[8, 0, 1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.041', ant_landscape: {} }} />
        <mesh name="SM_Env_Road_Bare_99042" geometry={nodes.SM_Env_Road_Bare_99042.geometry} material={materials.Road_01} position={[8, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002} userData={{ name: 'SM_Env_Road_Bare_99.042', ant_landscape: {} }} />
        <mesh name="trashcan005" geometry={nodes.trashcan005.geometry} material={materials.Synty_Palette_A} position={[-5.091, 0, 2.077]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'trashcan.005', ant_landscape: {} }} />
        <mesh name="SM_Prop_Manhole_29" geometry={nodes.SM_Prop_Manhole_29.geometry} material={materials.Synty_Palette_A} position={[0.48, 0, -0.439]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'SM_Prop_Manhole_29', ant_landscape: {} }} />
        <mesh name="SM_Prop_Manhole_29001" geometry={nodes.SM_Prop_Manhole_29001.geometry} material={materials.Synty_Palette_A} position={[-3.477, 0, -0.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'SM_Prop_Manhole_29.001', ant_landscape: {} }} />
        <mesh name="SM_Prop_Manhole_29009" geometry={nodes.SM_Prop_Manhole_29009.geometry} material={materials.Synty_Palette_A} position={[7.475, 0, -0.49]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'SM_Prop_Manhole_29.009', ant_landscape: {} }} />
        <mesh name="SM_Prop_Manhole_29010" geometry={nodes.SM_Prop_Manhole_29010.geometry} material={materials.Synty_Palette_A} position={[4.454, 0, -4.461]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'SM_Prop_Manhole_29.010', ant_landscape: {} }} />
        <mesh name="SM_Prop_Manhole_29011" geometry={nodes.SM_Prop_Manhole_29011.geometry} material={materials.Synty_Palette_A} position={[0.525, 0, -4.461]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'SM_Prop_Manhole_29.011', ant_landscape: {} }} />
        <mesh name="SM_Prop_SidewalkPoles_08011" geometry={nodes.SM_Prop_SidewalkPoles_08011.geometry} material={materials.Synty_Palette_A} position={[-4.904, 0.004, -0.478]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.002} userData={{ name: 'SM_Prop_SidewalkPoles_08.011', ant_landscape: {} }} />
        <mesh name="SM_Prop_SidewalkPoles_08012" geometry={nodes.SM_Prop_SidewalkPoles_08012.geometry} material={materials.Synty_Palette_A} position={[0.496, 0.004, -2.937]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'SM_Prop_SidewalkPoles_08.012', ant_landscape: {} }} />
        <mesh name="SM_Prop_SidewalkPoles_08001" geometry={nodes.SM_Prop_SidewalkPoles_08001.geometry} material={materials.Synty_Palette_A} position={[0.496, 0.004, 1.963]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'SM_Prop_SidewalkPoles_08.001', ant_landscape: {} }} />
        <mesh name="SM_Prop_SidewalkPoles_08002" geometry={nodes.SM_Prop_SidewalkPoles_08002.geometry} material={materials.Synty_Palette_A} position={[5.996, 0.004, -0.478]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.002} userData={{ name: 'SM_Prop_SidewalkPoles_08.002', ant_landscape: {} }} />
        <mesh name="trashcan001" geometry={nodes.trashcan001.geometry} material={materials.Synty_Palette_A} position={[2.609, 0, -2.175]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'trashcan.001', ant_landscape: {} }} />
        <mesh name="trashcan002" geometry={nodes.trashcan002.geometry} material={materials.Synty_Palette_A} position={[-0.957, 0, 1.625]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'trashcan.002', ant_landscape: {} }} />
        <mesh name="trashcan003" geometry={nodes.trashcan003.geometry} material={materials.Synty_Palette_A} position={[-6.299, 0, 1.425]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} userData={{ name: 'trashcan.003', ant_landscape: {} }} />
        <mesh name="park001" geometry={nodes.park001.geometry} material={materials.Synty_Palette_A} position={[0, 0, 3]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'park.001', ant_landscape: {} }} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/tutorial_01.glb'))
