/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tutorial_button.glb --output generated_components/tutorial_button.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    tutorial_button: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/tutorial_button.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <mesh name="tutorial_button" geometry={nodes.tutorial_button.geometry} material={materials['Material.003']} position={[-6.531, 1.43, 10.737]} rotation={[0.31, -0.342, 0.107]} scale={[1, 0.191, 1.055]} userData={{ name: 'tutorial_button' }} />
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/tutorial_button.glb'))
