/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vr_headset_02.glb --output generated_components/vr_headset_02.tsx --types --keepgroups --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getAssetPath } from '@/lib/assetPath'

type GLTFResult = GLTF & {
  nodes: {
    Strap_Cube002: THREE.Mesh
    Strap_Cube002_1: THREE.Mesh
    Strap_Cube002_2: THREE.Mesh
    Strap_Cube002_3: THREE.Mesh
    Strap_Cube002_4: THREE.Mesh
    Strap_Cube002_5: THREE.Mesh
  }
  materials: {
    ['Headset_M.001']: THREE.MeshStandardMaterial
    ['Strap.001']: THREE.MeshStandardMaterial
    ['Foam.001']: THREE.MeshStandardMaterial
    ['Gray_Plastic.001']: THREE.MeshStandardMaterial
    ['Lens.001']: THREE.MeshStandardMaterial
    ['L.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF(getAssetPath('models/vr_headset_02.glb')) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blosm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
        }}>
        <group name="headset001" position={[-3.38, 2.203, 10.625]} rotation={[Math.PI / 2, 0, -1.531]} scale={0.166} userData={{ name: 'headset.001', ant_landscape: {} }}>
          <mesh name="Strap_Cube002" geometry={nodes.Strap_Cube002.geometry} material={materials['Headset_M.001']} />
          <mesh name="Strap_Cube002_1" geometry={nodes.Strap_Cube002_1.geometry} material={materials['Strap.001']} />
          <mesh name="Strap_Cube002_2" geometry={nodes.Strap_Cube002_2.geometry} material={materials['Foam.001']} />
          <mesh name="Strap_Cube002_3" geometry={nodes.Strap_Cube002_3.geometry} material={materials['Gray_Plastic.001']} />
          <mesh name="Strap_Cube002_4" geometry={nodes.Strap_Cube002_4.geometry} material={materials['Lens.001']} />
          <mesh name="Strap_Cube002_5" geometry={nodes.Strap_Cube002_5.geometry} material={materials['L.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(getAssetPath('models/vr_headset_02.glb'))
